// HTTP transport for enquire-mcp.
//
// v2.6.0 — remote-MCP support. Runs the MCP server over Streamable HTTP
// (the protocol claude.ai web, ChatGPT, mobile clients, and Cursor's HTTP
// mode all use). Three layers in front of the SDK transport:
//
//   1. Bearer auth — constant-time token compare, fail-closed (401 on
//      missing/wrong header). Token is generated by the user (we never
//      mint tokens — this is not OAuth) and passed via --bearer-token or
//      --bearer-token-env. See docs/http-transport.md for the security
//      model and Tailscale Funnel / Cloudflare Tunnel deployment recipes.
//   2. Rate-limit — per-token sliding-window bucket, 429 on overflow.
//      In-memory; survives a single process. Default 120 req/min.
//   3. CORS — strict allowlist via --cors-origin (repeatable). Default
//      empty: no Access-Control-Allow-Origin header sent. Same-origin
//      and credentialed Bearer requests work either way.
//
// We use the SDK's StreamableHTTPServerTransport in stateless mode
// (sessionIdGenerator: undefined). A fresh transport + McpServer is
// connected per request. The Vault, FtsIndex, EmbedDb handles are
// SHARED across all sessions — opening SQLite once and reusing across
// thousands of remote-MCP calls. This is why prepareServerDeps() is
// called once in startHttpServer() and buildMcpServer() is called per
// request: the heavy I/O happens once at boot.
//
// Stateful sessions (sessionId-keyed transports) are deferred to v2.7+
// because they require persistence-aware shutdown handling and are only
// needed for SSE long-running operations. Our tools are short-running
// (search, read, frontmatter ops), so stateless is the right default.

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { createServer, type Server as HttpServer, type IncomingMessage, type ServerResponse } from "node:http";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { buildMcpServer, formatReadyBanner, prepareServerDeps, type ServeOptions, type ServerDeps } from "./index.js";
import { DEFAULT_MAX_FILE_BYTES } from "./vault.js";

/**
 * Configuration for the HTTP transport. Extends ServeOptions so every
 * stdio-mode flag (--enable-write, --persistent-index, --watch, etc.) is
 * available over HTTP too.
 */
export interface HttpServeOptions extends ServeOptions {
  /** TCP port to listen on. */
  port: number;
  /**
   * Bind host. Default 127.0.0.1 — explicit because remote-MCP must
   * opt-in to bind 0.0.0.0. Most users should keep it on localhost and
   * front it with Tailscale Funnel / Cloudflare Tunnel for remote access
   * (auth-and-encryption-in-depth). See docs/http-transport.md.
   */
  host: string;
  /**
   * Bearer token. Comparing constant-time. Required: a missing token
   * fails closed at startup (we refuse to bind without auth). Generate
   * with: `node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))"`.
   */
  bearerToken: string;
  /** URL path prefix for the MCP endpoint. Default `/mcp`. */
  mcpPath?: string;
  /** Max requests per minute per bearer token. Default 120. 0 disables. */
  rateLimitPerMinute?: number;
  /**
   * CORS origin allowlist. Repeatable. Default empty (no
   * Access-Control-Allow-Origin sent). Bearer-credentialed requests work
   * cross-origin only when the origin is in this list.
   */
  corsOrigins?: string[];
  /** Optional path-prefix to match a /health probe under (e.g. for Tailscale). Default `/health`. */
  healthPath?: string;
  /**
   * v2.14.0 — when `true`, the HTTP transport runs in stateful mode:
   * sessions are keyed by the `Mcp-Session-Id` header, each session has
   * its own `McpServer` + `StreamableHTTPServerTransport` pair, and
   * server-initiated notifications stream over a long-lived `GET /mcp`
   * SSE connection. Required for ChatGPT custom GPT actions and other
   * clients that expect persistent state across requests. Off by default
   * (stateless mode is the right choice for short-running tools and
   * minimizes attack surface).
   */
  stateful?: boolean;
  /**
   * v2.14.0 — when stateful, evict sessions idle longer than this many
   * milliseconds. Default 30 minutes. Sweep runs lazily on every
   * request (no separate timer). Idle = time since the last
   * `handleRequest` for that session.
   */
  sessionIdleTimeoutMs?: number;
  /**
   * v2.14.0 — max concurrent sessions. New sessions beyond this cap are
   * rejected with 503 + `Retry-After`. Default 100; protects against
   * memory exhaustion under adversarial create-and-abandon traffic.
   */
  maxSessions?: number;
  /**
   * When `true` (default), registers SIGINT/SIGTERM/beforeExit listeners
   * for graceful shutdown of the HTTP server, vault, FTS5 index, watcher,
   * and persistent cache. Tests pass `false` to avoid leaking listeners
   * when spawning many `startHttpServer()` instances in one process —
   * cleanup happens via `httpServer.close()` which still triggers the
   * underlying resource cleanup.
   */
  installSignalHandlers?: boolean;
}

/**
 * Sliding-window rate limiter. Per-token. Window is rolling 60 seconds.
 * Uses a tiny circular buffer of timestamps per token — O(burst-size)
 * memory per token, no GC churn (we trim when we check).
 *
 * NOT distributed. If the user runs multiple processes behind a load
 * balancer they'd want a shared store (Redis); deferred to v2.7+.
 */
class RateLimiter {
  private readonly perMinute: number;
  private readonly windows = new Map<string, number[]>();

  constructor(perMinute: number) {
    this.perMinute = perMinute;
  }

  /** Returns true if request allowed; false if over budget. */
  consume(tokenId: string, nowMs: number = Date.now()): boolean {
    if (this.perMinute <= 0) return true; // disabled
    const cutoff = nowMs - 60_000;
    let timestamps = this.windows.get(tokenId);
    if (!timestamps) {
      timestamps = [];
      this.windows.set(tokenId, timestamps);
    }
    // Trim out-of-window entries from the front (they're append-ordered).
    while (timestamps.length > 0 && (timestamps[0] ?? 0) < cutoff) {
      timestamps.shift();
    }
    if (timestamps.length >= this.perMinute) return false;
    timestamps.push(nowMs);
    return true;
  }

  /** Test-only: reset all windows. */
  reset(): void {
    this.windows.clear();
  }
}

/**
 * Constant-time bearer-token compare. The Authorization header is
 * `Bearer <token>` per RFC 6750. We compare against the raw token
 * supplied at startup — both sides padded to a hash so timingSafeEqual
 * doesn't leak length.
 *
 * Returns the SHA-256 digest of the token (used as the rate-limit key)
 * if valid, or null if not. We never use the raw token as the key — a
 * compromised log dump would expose it.
 */
function verifyBearer(authHeader: string | undefined, expectedToken: string): string | null {
  if (!authHeader?.startsWith("Bearer ")) return null;
  const presented = authHeader.slice("Bearer ".length).trim();
  if (presented.length === 0) return null;
  // Hash both sides so timingSafeEqual gets equal-length buffers regardless
  // of whether the presented token is longer or shorter than expected. The
  // hash is constant-length, so length-comparison short-circuits don't leak.
  const expectedHash = createHash("sha256").update(expectedToken).digest();
  const presentedHash = createHash("sha256").update(presented).digest();
  if (!timingSafeEqual(expectedHash, presentedHash)) return null;
  // Return the digest as the rate-limit key. Different tokens produce
  // different keys; the same token always produces the same key.
  return presentedHash.toString("hex").slice(0, 16);
}

/** Read the entire request body (UTF-8 JSON). Returns undefined for empty. */
async function readJsonBody(req: IncomingMessage, maxBytes: number): Promise<unknown> {
  const chunks: Buffer[] = [];
  let total = 0;
  for await (const chunk of req) {
    const buf = Buffer.from(chunk);
    total += buf.length;
    if (total > maxBytes) {
      throw new Error(`request body exceeds max ${maxBytes} bytes`);
    }
    chunks.push(buf);
  }
  if (total === 0) return undefined;
  const text = Buffer.concat(chunks).toString("utf8");
  return JSON.parse(text);
}

/**
 * v3.7.13 H2 — detect a JSON-RPC 2.0 `initialize` request without parsing
 * the full envelope. The body can be either a single message or a batch
 * (JSON-RPC permits arrays); we accept both, requiring AT LEAST ONE
 * element in a batch to be `method: "initialize"`. Returns false on
 * anything else (including malformed bodies — the caller has already
 * parsed JSON, so the shape is unknown but not parse-error territory).
 *
 * @internal — exported only for tests.
 */
export function isInitializeRequest(body: unknown): boolean {
  if (Array.isArray(body)) return body.some(isInitializeRequest);
  if (!body || typeof body !== "object") return false;
  const method = (body as { method?: unknown }).method;
  return method === "initialize";
}

/** Send a JSON-RPC error response with the given HTTP + RPC status. */
function sendJsonRpcError(res: ServerResponse, httpStatus: number, code: number, message: string): void {
  if (res.headersSent) return;
  res.statusCode = httpStatus;
  res.setHeader("Content-Type", "application/json");
  res.end(
    JSON.stringify({
      jsonrpc: "2.0",
      error: { code, message },
      id: null
    })
  );
}

/**
 * Apply CORS headers if the request's Origin is allowed.
 *
 * Defense-in-depth against the CORS-credentials-misconfig class of bugs:
 *
 *   • For an explicit allowlisted origin (e.g. https://claude.ai), we
 *     reflect ONLY that exact origin in `Access-Control-Allow-Origin` and
 *     emit `Vary: Origin` so caches don't cross-pollinate across origins.
 *     Pair with `Access-Control-Allow-Credentials: true` so cookies +
 *     credentialed Bearer requests work as expected.
 *
 *   • For the wildcard `*` allowlist entry, we reflect `*` literally (NOT
 *     the request's origin) and DO NOT send `Allow-Credentials: true`.
 *     Browsers reject the combo of wildcard-origin + credentials anyway,
 *     so this matches what they enforce. Equally important: it kills the
 *     CORS-credential-leak attack surface where a misconfigured wildcard
 *     could otherwise hand attacker.com a credential-bearing CORS grant.
 *
 *   • Disallowed origins get nothing — no Allow-Origin header → browser
 *     blocks the actual request even if we 200.
 *
 * Documented as a deliberate behavior split for users who pass `*`: with
 * `*` you get an unauthenticated public CORS endpoint (still bearer-gated
 * server-side, just no credentialed-cookie path). That's the right
 * trade-off.
 */
function applyCors(req: IncomingMessage, res: ServerResponse, allowOrigins: string[]): void {
  const requestOrigin = req.headers.origin;
  if (typeof requestOrigin !== "string") return;
  // Sourcing the response value from `allowOrigins` (a server-controlled
  // CLI flag) instead of from `req.headers.origin` (an attacker-controlled
  // request header) is a deliberate defense against the CORS-credential-
  // leak class of bug. CodeQL's `js/cors-misconfiguration-for-credentials`
  // query is satisfied because `matchedOrigin`'s data source is the
  // allowlist, not the request — even though the strings are equal by
  // construction at this point, the data-flow taint is what matters.
  const matchedOrigin = allowOrigins.find((o) => o === requestOrigin);
  const wildcardAllowed = matchedOrigin === undefined && allowOrigins.includes("*");
  if (matchedOrigin === undefined && !wildcardAllowed) return;
  // Wildcard branch: reflect literal "*" + OMIT Allow-Credentials (the
  // browser would reject the combo anyway, and we don't grant attacker
  // origins a credentialed window). Exact-match branch: use the trusted
  // allowlist value + send Allow-Credentials: true so cookies + Bearer
  // requests work cross-origin.
  if (wildcardAllowed) {
    res.setHeader("Access-Control-Allow-Origin", "*");
  } else if (matchedOrigin !== undefined) {
    res.setHeader("Access-Control-Allow-Origin", matchedOrigin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
  }
  res.setHeader("Vary", "Origin");
  res.setHeader("Access-Control-Allow-Methods", "POST, GET, DELETE, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Authorization, Content-Type, Mcp-Session-Id, Last-Event-ID");
  // v3.10.0-rc.62 (HTTP-CORS-EXPOSE-SESSION-ID) — `Access-Control-Allow-Headers` only lets a
  // browser SEND `Mcp-Session-Id` on the request; to let cross-origin JS READ the session id the
  // server returns on `initialize`, it must be listed in `Access-Control-Expose-Headers`. Without
  // this, a browser MCP client in stateful mode cannot capture the `Mcp-Session-Id` response header
  // and every follow-up request is treated as a new session (the SDK exposes it as a response header).
  res.setHeader("Access-Control-Expose-Headers", "Mcp-Session-Id");
  res.setHeader("Access-Control-Max-Age", "600");
}

/**
 * Build the request handler. Factored out of the listener-creation path
 * so tests can drive it without binding a TCP port.
 */
/**
 * v2.14.0 — one entry in the stateful-session map. Each session pairs an
 * `McpServer` instance with a `StreamableHTTPServerTransport` (in
 * stateful mode the SDK keys requests by the session id we assign at
 * `initialize` time) and tracks the last activity timestamp for
 * idle-eviction.
 *
 * v3.8.7 P2-10 — added `inFlight` refcount + `closing` flag to make
 * session lifecycle safe under concurrent requests:
 *   - `inFlight > 0` means at least one HTTP handler is currently
 *     awaiting `transport.handleRequest` on this session. The idle sweep
 *     skips such sessions even if their `lastActivityMs` is past the
 *     cutoff — closing a transport with an in-flight SSE/POST mid-stream
 *     produces broken responses and dangling McpServer state.
 *   - `closing` is set by the explicit shutdown paths (DELETE + sweep +
 *     `closeAll`) right before we begin teardown. Once true, the entry
 *     is also removed from `registry.sessions` so new gets return 404 —
 *     concurrent requests that already hold a `session` reference can
 *     finish naturally but won't be joined by new ones.
 */
interface StatefulSession {
  server: ReturnType<typeof buildMcpServer>;
  transport: InstanceType<typeof StreamableHTTPServerTransport>;
  /** Epoch-ms of the last `handleRequest` for this session. */
  lastActivityMs: number;
  /**
   * v3.8.7 — count of handlers currently inside `transport.handleRequest`
   * for this session. Incremented by `runWithRefcount`. Sweep + closeAll
   * wait for this to drop to 0 before tearing down the transport.
   */
  inFlight: number;
  /**
   * v3.8.7 — once set, the session is being torn down. The entry has
   * already been removed from `registry.sessions`; new requests will
   * 404. Existing in-flight requests are allowed to finish.
   */
  closing: boolean;
}

/**
 * v2.14.0 — exported for tests so they can poke at the session map
 * directly (idle eviction, max-cap, etc.) without spinning up a real
 * HTTP server.
 *
 * v3.8.7 P2-10/P2-11 — extended:
 *   - `pendingInits` makes the maxSessions cap-check atomic across
 *     concurrent initialize POSTs. The check is now
 *     `sessions.size + pendingInits >= maxSessions`. Each init handler
 *     increments before allocating server+transport and decrements in a
 *     finally. Without this, N concurrent inits could all pass the
 *     plain `size()` check and create N+ sessions.
 *   - `closeAll(timeoutMs)` is the graceful-shutdown drain: waits for
 *     in-flight requests up to `timeoutMs`, then closes every transport
 *     + McpServer pair. Used by `shutdownHttpServer` so tests +
 *     production both leave a clean process state (no leaked SQLite
 *     handles via the per-session embedder + watcher hooks).
 */
export interface SessionRegistry {
  readonly sessions: Map<string, StatefulSession>;
  /** Sweep idle sessions older than `idleTimeoutMs`. Returns evicted count. */
  sweepIdle(nowMs?: number): number;
  /** Total sessions currently tracked. */
  size(): number;
  /**
   * v3.8.7 — count of in-flight `initialize` POSTs that have passed the
   * cap-check but not yet been inserted into `sessions`. Used by the
   * cap-check to prevent the TOCTOU race where N concurrent inits all
   * see `size() < maxSessions` and overshoot. Public so tests can
   * assert it stays balanced (always returns to 0 after init resolves).
   */
  pendingInits: number;
  /**
   * v3.8.7 — graceful drain: mark all sessions as `closing`, wait up to
   * `timeoutMs` for in-flight requests to finish, then close every
   * transport + McpServer pair and clear the map. Returns the number of
   * sessions actually closed. Idempotent (second call is a no-op).
   */
  closeAll(timeoutMs?: number): Promise<number>;
}

export function createSessionRegistry(idleTimeoutMs: number): SessionRegistry {
  const sessions = new Map<string, StatefulSession>();
  const registry: SessionRegistry = {
    sessions,
    pendingInits: 0,
    sweepIdle(nowMs = Date.now()): number {
      const cutoff = nowMs - idleTimeoutMs;
      let evicted = 0;
      for (const [sid, session] of sessions) {
        if (session.closing) continue; // already being torn down
        // v3.8.7 P2-10 — skip in-flight sessions. Closing a transport
        // while a handler is awaiting handleRequest on it leaves the
        // response stream in an inconsistent state (the SDK's internal
        // queue still expects to drain). Next sweep will catch it once
        // the in-flight request finishes.
        if (session.inFlight > 0) continue;
        if (session.lastActivityMs < cutoff) {
          session.closing = true;
          sessions.delete(sid);
          // Best-effort cleanup — don't block on slow close.
          void session.transport.close().catch(() => {});
          void session.server.close().catch(() => {});
          evicted += 1;
        }
      }
      return evicted;
    },
    size: () => sessions.size,
    async closeAll(timeoutMs = 5000): Promise<number> {
      // Snapshot the sessions we're closing; mark `closing` synchronously
      // so new requests bounce with 404 while we drain in-flight.
      const snapshot = Array.from(sessions.values());
      for (const s of snapshot) s.closing = true;
      sessions.clear();
      // Wait (bounded) for in-flight handlers to finish naturally.
      const deadline = Date.now() + timeoutMs;
      while (Date.now() < deadline) {
        if (snapshot.every((s) => s.inFlight === 0)) break;
        await new Promise<void>((resolve) => setTimeout(resolve, 10));
      }
      // Close everything regardless — best-effort. After timeoutMs an
      // in-flight handler is "stuck" and we'd rather hand back the port
      // than wait forever.
      for (const s of snapshot) {
        await s.transport.close().catch(() => {});
        await s.server.close().catch(() => {});
      }
      return snapshot.length;
    }
  };
  return registry;
}

/**
 * v3.8.7 P2-10 — wrap a `handleRequest` call with the in-flight refcount.
 * The increment is synchronous (no `await` between increment + the work
 * starting), so the idle sweep can never see `inFlight === 0` while a
 * handler is mid-flight. The decrement runs in a `finally` so it fires
 * on both success + rejection paths.
 */
async function runWithRefcount<T>(session: StatefulSession, fn: () => Promise<T>): Promise<T> {
  session.inFlight += 1;
  try {
    return await fn();
  } finally {
    session.inFlight -= 1;
  }
}

/**
 * v3.10.0-rc.65 (round-3 audit) — wrap the stateful fresh-initialize body with the
 * `pendingInits` reservation so the decrement runs in a `finally` on EVERY exit path,
 * including a throw from `buildMcpServer` or the `StreamableHTTPServerTransport`
 * constructor. Pre-rc.65 the `pendingInits += 1` and both constructors sat OUTSIDE the
 * try/finally, so a constructor throw skipped the decrement → the counter leaked
 * permanently, lowering the effective `maxSessions` cap by one each time until every
 * `initialize` returned 503 even with zero live sessions (the documented "always returns
 * to 0 after init" invariant was violated). Exported so the balance is unit-testable
 * with an injected throwing `fn` (NEGATIVE control).
 */
export async function runWithPendingInit<T>(registry: SessionRegistry, fn: () => Promise<T>): Promise<T> {
  registry.pendingInits += 1;
  try {
    return await fn();
  } finally {
    registry.pendingInits -= 1;
  }
}

/**
 * v3.7.12 M4 — parse the `maxFileBytes` ServeOptions field WITHOUT calling
 * back into `prepareServerDeps` (we only need the parsed number, not the
 * full vault). Returns `undefined` for unset / malformed / non-positive
 * input so the caller falls back to `DEFAULT_MAX_FILE_BYTES`.
 *
 * @internal — exported only for tests.
 */
export function parseMaxFileBytes(raw: string | undefined): number | undefined {
  if (raw === undefined) return undefined;
  const n = Number(raw);
  if (!Number.isFinite(n) || n <= 0 || Math.floor(n) !== n) return undefined;
  return n;
}

/**
 * v3.7.12 M4 — derive the HTTP body-size cap from the vault's `maxFileBytes`
 * (or `DEFAULT_MAX_FILE_BYTES` when unset). Scales 1.5× to leave headroom
 * for the JSON-RPC envelope + string-escaping overhead, with a 4 MB floor
 * so tiny vaults don't shrink the cap below `tools/list` response size.
 *
 * @internal — exported only for tests.
 */
export function deriveHttpBodyCap(maxFileBytes: string | undefined): number {
  const vaultMaxBytes = parseMaxFileBytes(maxFileBytes) ?? DEFAULT_MAX_FILE_BYTES;
  return Math.max(4 * 1024 * 1024, Math.floor(vaultMaxBytes * 1.5));
}

export function createHttpHandler(
  deps: ServerDeps,
  opts: HttpServeOptions,
  /**
   * v3.8.7 P2-11 — optional out-param. If provided, the function
   * assigns `.registry` to the stateful-mode `SessionRegistry` (or
   * `null` in stateless mode). `startHttpServer` uses this to wire the
   * registry into the `shutdownHttpServer` helper via the
   * `httpServerExtras` WeakMap. Existing call sites that don't pass
   * `out` are unaffected (backwards compatible).
   */
  out?: { registry: SessionRegistry | null }
): (req: IncomingMessage, res: ServerResponse) => Promise<void> {
  const mcpPath = opts.mcpPath ?? "/mcp";
  const healthPath = opts.healthPath ?? "/health";
  const corsOrigins = opts.corsOrigins ?? [];
  const limiter = new RateLimiter(opts.rateLimitPerMinute ?? 120);
  // v3.7.12 M4 — body cap derived from the vault's `maxFileBytes` via
  // `deriveHttpBodyCap`. Previously hardcoded 4 MB, which was BELOW the default
  // per-file cap of 5 MB — a `create_note` with a 4.5 MB payload would clear
  // `Vault.assertSize` but be rejected at the HTTP layer with a confusing 413.
  const maxBodyBytes = deriveHttpBodyCap(opts.maxFileBytes);

  // v2.14.0 stateful-mode state.
  const stateful = opts.stateful === true;
  const idleTimeoutMs = opts.sessionIdleTimeoutMs ?? 30 * 60 * 1000; // 30 min default
  const maxSessions = opts.maxSessions ?? 100;
  const registry = stateful ? createSessionRegistry(idleTimeoutMs) : null;
  if (out) out.registry = registry;

  return async (req, res) => {
    try {
      applyCors(req, res, corsOrigins);

      // OPTIONS preflight short-circuit.
      if (req.method === "OPTIONS") {
        res.statusCode = 204;
        res.end();
        return;
      }

      const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);

      // Health probe — unauthenticated, no rate-limit. Useful for
      // Tailscale/Cloudflare healthchecks. Returns just `ok` so it
      // doesn't leak version info to unauth callers.
      if (url.pathname === healthPath && req.method === "GET") {
        res.statusCode = 200;
        res.setHeader("Content-Type", "text/plain");
        res.end("ok");
        return;
      }

      if (url.pathname !== mcpPath) {
        res.statusCode = 404;
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "not found", path: url.pathname }));
        return;
      }

      // Auth: bearer token required for /mcp.
      const authHeader = req.headers.authorization;
      const tokenKey = verifyBearer(typeof authHeader === "string" ? authHeader : undefined, opts.bearerToken);
      if (tokenKey === null) {
        res.statusCode = 401;
        res.setHeader("WWW-Authenticate", 'Bearer realm="enquire-mcp"');
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "unauthorized" }));
        return;
      }

      // Rate-limit per token.
      if (!limiter.consume(tokenKey)) {
        res.statusCode = 429;
        res.setHeader("Retry-After", "60");
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "rate limit exceeded" }));
        return;
      }

      // Stateless mode (default) — POST only; fresh server+transport
      // per request. Same path as v2.6.0.
      if (!stateful || !registry) {
        if (req.method !== "POST") {
          sendJsonRpcError(res, 405, -32000, `Method ${req.method} not allowed for ${mcpPath}`);
          return;
        }
        await handleStatelessRequest(req, res, deps, opts, maxBodyBytes);
        return;
      }

      // ─── v2.14.0 stateful mode ─────────────────────────────────────────
      // Lazy idle-sweep on every request. Bounded work — at most O(|sessions|)
      // and cheap (Date compare per entry).
      registry.sweepIdle();

      const sessionIdHeader = req.headers["mcp-session-id"];
      const sessionId = typeof sessionIdHeader === "string" ? sessionIdHeader : undefined;

      // DELETE /mcp — explicit session termination. SDK's transport
      // handles the protocol-level details; we just route it.
      if (req.method === "DELETE") {
        if (!sessionId) {
          sendJsonRpcError(res, 400, -32000, "DELETE requires Mcp-Session-Id header");
          return;
        }
        const session = registry.sessions.get(sessionId);
        if (!session || session.closing) {
          // Idempotent — if the session is already gone (or being torn
          // down), treat as success.
          res.statusCode = 204;
          res.end();
          return;
        }
        // v3.8.7 P2-10 — mark closing + remove from map BEFORE handleRequest.
        // Concurrent gets that arrive during the SDK's protocol-level
        // shutdown then 404 instead of joining a half-closed session.
        // The DELETE itself is in-flight, so we increment the refcount;
        // the actual close waits for that (and any pre-existing in-flight)
        // to drain. (Snapshot the entry locally first — `delete` removes
        // it from the map but the entry stays referenced by `session`.)
        session.closing = true;
        registry.sessions.delete(sessionId);
        try {
          await runWithRefcount(session, () => session.transport.handleRequest(req, res));
        } catch {
          /* shutdown errors don't matter — we're killing the session anyway */
        }
        // Drain other in-flight (e.g. an SSE GET held the refcount up)
        // up to a small bound, then close. The bound matches closeAll's
        // default — long enough for normal completion, short enough that
        // a stuck client doesn't pin the McpServer + SQLite handles.
        const deadline = Date.now() + 5000;
        while (session.inFlight > 0 && Date.now() < deadline) {
          await new Promise<void>((resolve) => setTimeout(resolve, 10));
        }
        await session.transport.close().catch(() => {});
        await session.server.close().catch(() => {});
        return;
      }

      // GET /mcp — long-lived SSE stream for server-initiated
      // notifications. The transport handles the SSE framing; we just
      // route the request to the right session.
      if (req.method === "GET") {
        if (!sessionId) {
          sendJsonRpcError(res, 400, -32000, "GET requires Mcp-Session-Id header (initialize first)");
          return;
        }
        const session = registry.sessions.get(sessionId);
        // v3.8.7 P2-10 — also reject `closing` sessions. A closing entry
        // has been removed from `sessions` so this branch is normally
        // unreachable, but the explicit check documents intent + keeps
        // us safe if someone later changes when `closing` is set.
        if (!session || session.closing) {
          sendJsonRpcError(res, 404, -32000, `Unknown session ${sessionId}`);
          return;
        }
        session.lastActivityMs = Date.now();
        try {
          await runWithRefcount(session, () => session.transport.handleRequest(req, res));
        } catch (err) {
          process.stderr.write(`enquire http: SSE error — ${err instanceof Error ? err.message : String(err)}\n`);
        }
        return;
      }

      if (req.method !== "POST") {
        sendJsonRpcError(res, 405, -32000, `Method ${req.method} not allowed for ${mcpPath}`);
        return;
      }

      // POST /mcp — either an existing session (Mcp-Session-Id header)
      // or a new initialize. Read the body once; we'll need it to
      // detect initialize and to feed handleRequest.
      let body: unknown;
      try {
        body = await readJsonBody(req, maxBodyBytes);
      } catch (err) {
        sendJsonRpcError(res, 400, -32700, err instanceof Error ? err.message : "Parse error");
        return;
      }

      if (sessionId) {
        // Existing session — route to its transport.
        const session = registry.sessions.get(sessionId);
        // v3.8.7 P2-10 — same `closing` defense as the GET branch. A
        // session marked `closing` is mid-shutdown and not safe to use.
        if (!session || session.closing) {
          sendJsonRpcError(res, 404, -32000, `Unknown session ${sessionId} (it may have expired)`);
          return;
        }
        session.lastActivityMs = Date.now();
        try {
          await runWithRefcount(session, () => session.transport.handleRequest(req, res, body));
        } catch (err) {
          process.stderr.write(
            `enquire http: stateful transport error — ${err instanceof Error ? err.message : String(err)}\n`
          );
          if (!res.headersSent) {
            sendJsonRpcError(res, 500, -32603, "Internal server error");
          }
        }
        return;
      }

      // No session id — must be a fresh `initialize`. Cap before allocating.
      // v3.8.7 P2-10 — include `pendingInits` so concurrent inits that
      // have passed this check but not yet inserted into `sessions`
      // count toward the cap. Without this, the check is a TOCTOU race
      // (N concurrent inits all see `size() < maxSessions` and overshoot).
      if (registry.size() + registry.pendingInits >= maxSessions) {
        res.statusCode = 503;
        res.setHeader("Retry-After", "60");
        res.setHeader("Content-Type", "application/json");
        res.end(
          JSON.stringify({
            error: "max sessions reached",
            current: registry.size(),
            max: maxSessions
          })
        );
        return;
      }

      // v3.7.13 H2 — verify the body is an `initialize` JSON-RPC request
      // BEFORE we allocate a server + transport. Pre-3.7.13, any POST
      // without `Mcp-Session-Id` allocated both, then handed the body to
      // the SDK; if the body wasn't `initialize`, the SDK would either
      // reject internally or surface a protocol error — but in some
      // failure modes `onsessioninitialized` never fires and cleanup
      // never runs, leaking the McpServer + transport pair. Bearer-token
      // DoS: not anonymous, but easy for any client with a valid token
      // to fire create-and-abandon traffic until `maxSessions` blocks
      // further work. This pre-validation short-circuits the leak by
      // rejecting non-initialize POSTs at the JSON-RPC level before any
      // allocation.
      if (!isInitializeRequest(body)) {
        sendJsonRpcError(
          res,
          400,
          -32600,
          "First POST without Mcp-Session-Id header must be a JSON-RPC `initialize` request"
        );
        return;
      }

      // v3.8.7 P2-10 + v3.10.0-rc.65 — reserve the slot synchronously and run the WHOLE
      // build+connect+initialize under `runWithPendingInit`, so the reservation is released on
      // EVERY exit path — including a throw from `buildMcpServer` or the
      // `StreamableHTTPServerTransport` constructor (pre-rc.65 those ran BEFORE the try/finally,
      // so a constructor throw leaked `pendingInits` permanently → eventual 503). Between the
      // reservation and the `onsessioninitialized` callback the cap-check above can see it via
      // `pendingInits` and reject concurrent inits that would overshoot the cap.
      await runWithPendingInit(registry, async () => {
        // The session object is constructed up-front so `onsessioninitialized` can insert it
        // atomically and the refcount wrapper can use it during the initialize POST itself.
        // Declared `let` + undefined so the catch can clean up PARTIAL state if a constructor
        // throws (rc.65 — the constructors are now inside the try, not before it).
        let server: ReturnType<typeof buildMcpServer> | undefined;
        let session: StatefulSession | undefined;
        let transport: InstanceType<typeof StreamableHTTPServerTransport> | undefined;
        try {
          server = buildMcpServer(deps, opts);
          session = {
            server,
            // Filled in below once `transport` is constructed.
            transport: null as unknown as InstanceType<typeof StreamableHTTPServerTransport>,
            lastActivityMs: Date.now(),
            inFlight: 0,
            closing: false
          };
          const sess = session; // captured (definitely-assigned) for the SDK callbacks
          transport = new StreamableHTTPServerTransport({
            sessionIdGenerator: () => randomBytes(16).toString("hex"),
            onsessioninitialized: (sid: string) => {
              // The SDK guarantees this fires before initialize's response
              // ships, so the entry exists when subsequent requests arrive.
              registry.sessions.set(sid, sess);
            }
          });
          session.transport = transport;
          const tr = transport; // captured (definitely-assigned) for the onclose closure
          // Wire up cleanup on transport close (e.g. client disconnect mid-stream).
          tr.onclose = () => {
            const sid = tr.sessionId;
            if (sid) {
              const tracked = registry.sessions.get(sid);
              // v3.8.7 P2-10 — only mark + delete if WE inserted this entry.
              // (Defensive — onclose can fire after closeAll already removed it.)
              if (tracked) {
                tracked.closing = true;
                registry.sessions.delete(sid);
              }
            }
          };
          await server.connect(tr);
          await runWithRefcount(session, () => tr.handleRequest(req, res, body));
        } catch (err) {
          process.stderr.write(
            `enquire http: stateful initialize error — ${err instanceof Error ? err.message : String(err)}\n`
          );
          // Best-effort: free whatever we allocated (each guarded — a constructor may have
          // thrown before the later ones ran). If the session was already registered, mark it
          // closing + drop from map so concurrent requests don't grab a half-dead entry.
          if (session) session.closing = true;
          const sid = transport?.sessionId;
          if (sid) registry.sessions.delete(sid);
          if (transport) void transport.close().catch(() => {});
          if (server) void server.close().catch(() => {});
          if (!res.headersSent) {
            sendJsonRpcError(res, 500, -32603, "Internal server error");
          }
        }
      });
    } catch (err) {
      // Final safety net — if anything in the outer block throws (URL
      // parse, header read), don't leave the connection hung.
      process.stderr.write(
        `enquire http: handler error — ${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`
      );
      if (!res.headersSent) {
        sendJsonRpcError(res, 500, -32603, "Internal server error");
      }
    }
  };
}

/**
 * Stateless POST handler — extracted from createHttpHandler so the
 * stateful path can keep using fresh server+transport per non-session
 * request when we want to (we don't currently). Identical to the
 * v2.6.0 default flow.
 */
async function handleStatelessRequest(
  req: IncomingMessage,
  res: ServerResponse,
  deps: ServerDeps,
  opts: HttpServeOptions,
  maxBodyBytes: number
): Promise<void> {
  let body: unknown;
  try {
    body = await readJsonBody(req, maxBodyBytes);
  } catch (err) {
    sendJsonRpcError(res, 400, -32700, err instanceof Error ? err.message : "Parse error");
    return;
  }
  const server = buildMcpServer(deps, opts);
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
  // v3.9.0-rc.16 — register cleanup BEFORE connect + make it idempotent +
  // error-safe, for parity with the stateful path's close discipline (P2-10).
  // Pre-rc.16 the `res.on("close")` registration sat AFTER `server.connect()`,
  // so a connect failure threw straight to the catch and the freshly-built
  // server + transport leaked (cleanup was never wired). The `cleanedUp` guard
  // prevents the double-close that a `res 'close'` + catch both firing would
  // otherwise cause; the `.catch` mirrors the stateful arms (lines ~378/402).
  let cleanedUp = false;
  const cleanup = () => {
    if (cleanedUp) return;
    cleanedUp = true;
    void transport.close().catch(() => {});
    void server.close().catch(() => {});
  };
  res.on("close", cleanup);
  try {
    await server.connect(transport);
    await transport.handleRequest(req, res, body);
  } catch (err) {
    process.stderr.write(`enquire http: transport error — ${err instanceof Error ? err.message : String(err)}\n`);
    if (!res.headersSent) {
      sendJsonRpcError(res, 500, -32603, "Internal server error");
    }
    // Belt-and-suspenders: if the response stream never emits 'close' (e.g.
    // connect threw before the socket was wired), free the handles now.
    cleanup();
  }
}

/**
 * Generate a fresh 32-byte base64url bearer token. Used by the
 * `enquire-mcp gen-token` subcommand.
 */
export function generateBearerToken(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * v3.8.7 P2-11 — track the SessionRegistry + ServerDeps associated with
 * each `http.Server` we hand back from `startHttpServer`. WeakMap keys
 * means we don't pin the server in memory after it's gone.
 *
 * Used by `shutdownHttpServer(server)` so callers (tests + the
 * SIGINT/SIGTERM handlers below) can drain in-flight sessions + close
 * underlying SQLite/watcher resources without threading the dep handles
 * back through their own code.
 */
interface HttpServerExtras {
  /** Stateful-mode registry; null in stateless mode. */
  registry: SessionRegistry | null;
  /** Server deps so shutdownHttpServer can close watcher/fts/embed-db cleanly. */
  deps: ServerDeps;
}
const httpServerExtras = new WeakMap<HttpServer, HttpServerExtras>();

/**
 * v3.10.0-rc.23 — bounded grace for `server.close()`. Node's
 * `http.Server.close()` callback fires only once EVERY connection has ended, and
 * it does NOT terminate idle keep-alive sockets — so a client / reverse-proxy
 * (or a half-open socket) holding a connection open makes `close()` hang
 * indefinitely. We immediately close idle keep-alives, then force-close any
 * straggler after this grace, so shutdown can never block forever.
 *
 * This is the bound whose absence turned rc.19's signal-handler consolidation
 * into a hang: pre-rc.19 a cache-flush handler called `process.exit(0)` on its
 * own (masking the latent `close()` hang); rc.19 correctly made shutdown AWAIT
 * the full drain — but without this cap, "await the drain" became "await
 * forever" whenever a connection lingered (reproduced: a lingering socket +
 * SIGTERM hung `serve-http` indefinitely).
 */
const HTTP_CLOSE_GRACE_MS = 3000;

/** Close an `http.Server` with a bounded grace (see {@link HTTP_CLOSE_GRACE_MS}).
 *  Resolves as soon as `close()` completes, or after `graceMs` once stragglers
 *  are force-closed — never hangs on a lingering keep-alive connection.
 *  `graceMs` is injectable for tests; production callers use the default. */
export function closeServerBounded(server: HttpServer, graceMs: number = HTTP_CLOSE_GRACE_MS): Promise<void> {
  return new Promise<void>((resolve) => {
    const grace = setTimeout(() => {
      // Force-close active stragglers (Node ≥18.2; engines floor is ≥22.13).
      try {
        server.closeAllConnections();
      } catch {
        /* already closed / unavailable */
      }
    }, graceMs);
    if (typeof grace.unref === "function") grace.unref();
    server.close(() => {
      clearTimeout(grace);
      resolve();
    });
    // Idle keep-alive sockets won't end on their own; close them now so the
    // common case (no in-flight request) resolves immediately rather than
    // waiting out the grace.
    try {
      server.closeIdleConnections();
    } catch {
      /* best-effort */
    }
  });
}

/**
 * v3.8.7 P2-11 — graceful shutdown helper for an `http.Server` returned
 * by {@link startHttpServer}. Drains stateful sessions (if any), closes
 * the underlying TCP listener, then closes vault/fts/watcher/embed-db
 * handles owned by `prepareServerDeps`.
 *
 * Without this, callers that pass `installSignalHandlers: false` (the
 * test path, plus anyone managing the process lifecycle externally)
 * would silently leak: `httpServer.close()` alone closes only the TCP
 * accept loop, NOT the per-session McpServer + transport pairs in
 * stateful mode, and NOT the vault/fts/embed-db SQLite handles that
 * `prepareServerDeps` opens once at boot.
 *
 * Order matters:
 *   1. `registry.closeAll()` — bounded wait for in-flight requests to
 *      finish, then close every transport + McpServer in stateful mode.
 *   2. `httpServer.close()` — stop accepting new connections + wait for
 *      existing ones to drain. Node's http.Server doesn't actively
 *      terminate keep-alive sockets unless we ask it to.
 *   3. Close vault, fts5 index, watcher, watcherEmbedDb — same order
 *      as the SIGINT cleanup chain in startHttpServer.
 *
 * Idempotent: a second call on the same server is a no-op once extras
 * are unset.
 */
export async function shutdownHttpServer(server: HttpServer): Promise<void> {
  const extras = httpServerExtras.get(server);
  if (!extras) {
    // Already cleaned up (or not from startHttpServer). Still close the
    // TCP listener for safety.
    await closeServerBounded(server);
    return;
  }
  httpServerExtras.delete(server);
  try {
    if (extras.registry) {
      await extras.registry.closeAll().catch(() => {});
    }
  } catch {
    /* best-effort */
  }
  await closeServerBounded(server);
  // Close deps last — they own SQLite + chokidar handles that should
  // outlive in-flight requests (which we drained above). Vault doesn't
  // own a SQLite handle (no `close()` method), but it owns the
  // persistent disk cache that we should flush before exit so a
  // SIGKILL-followed-by-cold-start doesn't reread an empty vault.
  // v3.10.0-rc.44 (M6) — ORDER MATTERS, and now mirrors shutdownStdioDeps. Drain the
  // watcher FIRST, while ftsIndex + watcherEmbedDb are still OPEN: an in-flight / late
  // chokidar handler calls ftsIndex.reindexFile/dropFile + embed-db ops, and
  // watcher.close()'s flushHnswToDisk calls embedDb.computeSignature(). Pre-rc.44
  // ftsIndex.close() ran BEFORE the drain, so a handler still in flight during the
  // closeAll(5s)+closeServerBounded(3s) window threw on a closed SQLite handle and the
  // whole event (fts + embed + hnsw) was dropped. Then close the watcher's embed-db,
  // flush the vault cache, and close fts LAST.
  try {
    await extras.deps.watcher?.close();
  } catch {
    /* best-effort */
  }
  try {
    extras.deps.watcherEmbedDb?.close();
  } catch {
    /* best-effort */
  }
  if (extras.deps.vault.persistentCacheEnabled) {
    try {
      await extras.deps.vault.saveDiskCache();
    } catch {
      /* best-effort */
    }
  }
  try {
    extras.deps.ftsIndex?.close();
  } catch {
    /* best-effort */
  }
}

/**
 * v3.10.0-rc.19 (audit M3) — single SIGINT/SIGTERM orchestrator for the HTTP
 * transport. Returns a handler that awaits the FULL graceful teardown
 * ({@link shutdownHttpServer}: drain in-flight stateful sessions up to
 * `closeAll`'s bound → close the TCP listener → flush the persistent cache →
 * close fts/watcher/embed-db) and only THEN calls `exit`.
 *
 * Before rc.19, SIGINT/SIGTERM had FOUR separate listeners registered on the
 * same signal: a cache-`flush` handler, a `closeWatcher` handler, a `closeFts`
 * handler, AND the `shutdownHttpServer` handler. The flush handler called
 * `process.exit(0)` the moment its (fast) `saveDiskCache` resolved — racing
 * ahead of `shutdownHttpServer`'s up-to-5s session drain and cutting off
 * in-flight requests. The other three handlers were also pure redundancy:
 * `shutdownHttpServer` already flushes the cache and closes fts/watcher/embed-db
 * itself. Consolidating to ONE handler that awaits the whole chain removes the
 * race and the duplication.
 *
 * `exit` is injectable for tests (default `process.exit`). The returned handler
 * guards re-entry so a SIGINT-then-SIGTERM (or a double signal) can't kick off
 * two concurrent teardowns or two `exit` calls.
 */
export function makeHttpShutdownHandler(
  server: HttpServer,
  exit: (code: number) => void = (code) => process.exit(code)
): () => void {
  let running = false;
  return () => {
    if (running) return;
    running = true;
    void shutdownHttpServer(server)
      .catch(() => {
        /* best-effort — never block exit on a teardown error */
      })
      .finally(() => exit(0));
  };
}

/**
 * Bind and start the HTTP transport. Returns the underlying http.Server
 * so callers (tests + CLI) can listen for `listening` / close it.
 */
export async function startHttpServer(opts: HttpServeOptions): Promise<HttpServer> {
  if (!opts.bearerToken || opts.bearerToken.length < 16) {
    throw new Error(
      "enquire serve-http: --bearer-token is required and must be ≥16 chars. " +
        "Generate one with: enquire-mcp gen-token"
    );
  }
  const deps = await prepareServerDeps(opts);
  // v3.8.7 P2-11 — capture the stateful registry via the out-param so
  // we can wire it into `shutdownHttpServer` via the WeakMap below.
  const handlerOut: { registry: SessionRegistry | null } = { registry: null };
  const handler = createHttpHandler(deps, opts, handlerOut);
  const httpServer = createServer((req, res) => {
    void handler(req, res);
  });
  httpServerExtras.set(httpServer, { registry: handlerOut.registry, deps });

  // v3.10.0-rc.19 (audit M3) — ONE graceful-shutdown orchestrator on signal.
  // `shutdownHttpServer` already drains in-flight stateful sessions, closes the
  // TCP listener, flushes the persistent cache, and closes fts/watcher/embed-db,
  // so a single handler that AWAITS it (then exits) replaces the four separate
  // pre-rc.19 listeners (flush / closeWatcher / closeFts / shutdown). The old
  // flush listener called `process.exit(0)` the moment its fast cache flush
  // resolved — racing ahead of the up-to-5s session drain and cutting off
  // in-flight requests; the other three were pure duplication of work
  // shutdownHttpServer already does. Skipped under installSignalHandlers=false
  // so tests can spawn many servers in one process without accumulating
  // SIGINT/SIGTERM listeners.
  if (opts.installSignalHandlers !== false) {
    const onSignal = makeHttpShutdownHandler(httpServer);
    process.once("SIGINT", onSignal);
    process.once("SIGTERM", onSignal);
    // beforeExit (natural drain, no signal): best-effort teardown, never exit.
    // Idempotent via shutdownHttpServer's WeakMap-delete; guarded so the async
    // teardown it schedules can't make beforeExit re-fire in a loop.
    let beforeExitRan = false;
    process.on("beforeExit", () => {
      if (beforeExitRan) return;
      beforeExitRan = true;
      void shutdownHttpServer(httpServer).catch(() => {});
    });
  }

  await new Promise<void>((resolve, reject) => {
    httpServer.once("error", reject);
    httpServer.listen(opts.port, opts.host, () => {
      httpServer.removeListener("error", reject);
      resolve();
    });
  }).catch(async (err) => {
    // v3.10.0-rc.70 (round-3 re-sweep, reserve-before-try) — a listen() failure (EADDRINUSE /
    // EACCES on a privileged port) happens AFTER prepareServerDeps already opened the fts5 +
    // watcher-embed-db SQLite handles and started the chokidar watcher (recorded in the
    // httpServerExtras WeakMap above). Nothing else calls shutdownHttpServer on a synchronous
    // boot throw (the signal handlers never fire), so close those deps before re-throwing rather
    // than leak them until the process exits.
    await shutdownHttpServer(httpServer).catch(() => {});
    throw err;
  });

  const addr = httpServer.address();
  const bound =
    addr && typeof addr === "object"
      ? `http://${addr.address === "::" ? "::" : addr.address}:${addr.port}`
      : `http://${opts.host}:${opts.port}`;
  const corsLabel = (opts.corsOrigins?.length ?? 0) > 0 ? `, cors=${opts.corsOrigins?.length ?? 0}` : "";
  const rateLabel = (opts.rateLimitPerMinute ?? 120) > 0 ? `, rate-limit=${opts.rateLimitPerMinute ?? 120}/min` : "";
  process.stderr.write(
    `${formatReadyBanner(deps)} (transport=http, bound=${bound}${opts.mcpPath ?? "/mcp"}${corsLabel}${rateLabel})\n`
  );
  return httpServer;
}

// Re-export the rate limiter and helpers for tests.
export { RateLimiter, readJsonBody, verifyBearer };
