// HTTP transport for enquire-mcp.
//
// v2.6.0 — remote-MCP support. Runs the MCP server over Streamable HTTP
// (the protocol claude.ai web, ChatGPT, mobile clients, and Cursor's HTTP
// mode all use). Three layers in front of the SDK transport:
//
//   1. Bearer auth — constant-time token compare, fail-closed (401 on
//      missing/wrong header). Token is generated by the user (we never
//      mint tokens — this is not OAuth) and passed via --bearer-token or
//      --bearer-token-env. See docs/http-transport.md for the security
//      model and Tailscale Funnel / Cloudflare Tunnel deployment recipes.
//   2. Rate-limit — per-token sliding-window bucket, 429 on overflow.
//      In-memory; survives a single process. Default 120 req/min.
//   3. CORS — strict allowlist via --cors-origin (repeatable). Default
//      empty: no Access-Control-Allow-Origin header sent. Same-origin
//      and credentialed Bearer requests work either way.
//
// We use the SDK's StreamableHTTPServerTransport in stateless mode
// (sessionIdGenerator: undefined). A fresh transport + McpServer is
// connected per request. The Vault, FtsIndex, EmbedDb handles are
// SHARED across all sessions — opening SQLite once and reusing across
// thousands of remote-MCP calls. This is why prepareServerDeps() is
// called once in startHttpServer() and buildMcpServer() is called per
// request: the heavy I/O happens once at boot.
//
// Stateful sessions (sessionId-keyed transports) are deferred to v2.7+
// because they require persistence-aware shutdown handling and are only
// needed for SSE long-running operations. Our tools are short-running
// (search, read, frontmatter ops), so stateless is the right default.

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { createServer, type Server as HttpServer, type IncomingMessage, type ServerResponse } from "node:http";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { buildMcpServer, formatReadyBanner, prepareServerDeps, type ServeOptions, type ServerDeps } from "./index.js";

/**
 * Configuration for the HTTP transport. Extends ServeOptions so every
 * stdio-mode flag (--enable-write, --persistent-index, --watch, etc.) is
 * available over HTTP too.
 */
export interface HttpServeOptions extends ServeOptions {
  /** TCP port to listen on. */
  port: number;
  /**
   * Bind host. Default 127.0.0.1 — explicit because remote-MCP must
   * opt-in to bind 0.0.0.0. Most users should keep it on localhost and
   * front it with Tailscale Funnel / Cloudflare Tunnel for remote access
   * (auth-and-encryption-in-depth). See docs/http-transport.md.
   */
  host: string;
  /**
   * Bearer token. Comparing constant-time. Required: a missing token
   * fails closed at startup (we refuse to bind without auth). Generate
   * with: `node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))"`.
   */
  bearerToken: string;
  /** URL path prefix for the MCP endpoint. Default `/mcp`. */
  mcpPath?: string;
  /** Max requests per minute per bearer token. Default 120. 0 disables. */
  rateLimitPerMinute?: number;
  /**
   * CORS origin allowlist. Repeatable. Default empty (no
   * Access-Control-Allow-Origin sent). Bearer-credentialed requests work
   * cross-origin only when the origin is in this list.
   */
  corsOrigins?: string[];
  /** Optional path-prefix to match a /health probe under (e.g. for Tailscale). Default `/health`. */
  healthPath?: string;
  /**
   * When `true` (default), registers SIGINT/SIGTERM/beforeExit listeners
   * for graceful shutdown of the HTTP server, vault, FTS5 index, watcher,
   * and persistent cache. Tests pass `false` to avoid leaking listeners
   * when spawning many `startHttpServer()` instances in one process —
   * cleanup happens via `httpServer.close()` which still triggers the
   * underlying resource cleanup.
   */
  installSignalHandlers?: boolean;
}

/**
 * Sliding-window rate limiter. Per-token. Window is rolling 60 seconds.
 * Uses a tiny circular buffer of timestamps per token — O(burst-size)
 * memory per token, no GC churn (we trim when we check).
 *
 * NOT distributed. If the user runs multiple processes behind a load
 * balancer they'd want a shared store (Redis); deferred to v2.7+.
 */
class RateLimiter {
  private readonly perMinute: number;
  private readonly windows = new Map<string, number[]>();

  constructor(perMinute: number) {
    this.perMinute = perMinute;
  }

  /** Returns true if request allowed; false if over budget. */
  consume(tokenId: string, nowMs: number = Date.now()): boolean {
    if (this.perMinute <= 0) return true; // disabled
    const cutoff = nowMs - 60_000;
    let timestamps = this.windows.get(tokenId);
    if (!timestamps) {
      timestamps = [];
      this.windows.set(tokenId, timestamps);
    }
    // Trim out-of-window entries from the front (they're append-ordered).
    while (timestamps.length > 0 && (timestamps[0] ?? 0) < cutoff) {
      timestamps.shift();
    }
    if (timestamps.length >= this.perMinute) return false;
    timestamps.push(nowMs);
    return true;
  }

  /** Test-only: reset all windows. */
  reset(): void {
    this.windows.clear();
  }
}

/**
 * Constant-time bearer-token compare. The Authorization header is
 * `Bearer <token>` per RFC 6750. We compare against the raw token
 * supplied at startup — both sides padded to a hash so timingSafeEqual
 * doesn't leak length.
 *
 * Returns the SHA-256 digest of the token (used as the rate-limit key)
 * if valid, or null if not. We never use the raw token as the key — a
 * compromised log dump would expose it.
 */
function verifyBearer(authHeader: string | undefined, expectedToken: string): string | null {
  if (!authHeader?.startsWith("Bearer ")) return null;
  const presented = authHeader.slice("Bearer ".length).trim();
  if (presented.length === 0) return null;
  // Hash both sides so timingSafeEqual gets equal-length buffers regardless
  // of whether the presented token is longer or shorter than expected. The
  // hash is constant-length, so length-comparison short-circuits don't leak.
  const expectedHash = createHash("sha256").update(expectedToken).digest();
  const presentedHash = createHash("sha256").update(presented).digest();
  if (!timingSafeEqual(expectedHash, presentedHash)) return null;
  // Return the digest as the rate-limit key. Different tokens produce
  // different keys; the same token always produces the same key.
  return presentedHash.toString("hex").slice(0, 16);
}

/** Read the entire request body (UTF-8 JSON). Returns undefined for empty. */
async function readJsonBody(req: IncomingMessage, maxBytes: number): Promise<unknown> {
  const chunks: Buffer[] = [];
  let total = 0;
  for await (const chunk of req) {
    const buf = Buffer.from(chunk);
    total += buf.length;
    if (total > maxBytes) {
      throw new Error(`request body exceeds max ${maxBytes} bytes`);
    }
    chunks.push(buf);
  }
  if (total === 0) return undefined;
  const text = Buffer.concat(chunks).toString("utf8");
  return JSON.parse(text);
}

/** Send a JSON-RPC error response with the given HTTP + RPC status. */
function sendJsonRpcError(res: ServerResponse, httpStatus: number, code: number, message: string): void {
  if (res.headersSent) return;
  res.statusCode = httpStatus;
  res.setHeader("Content-Type", "application/json");
  res.end(
    JSON.stringify({
      jsonrpc: "2.0",
      error: { code, message },
      id: null
    })
  );
}

/**
 * Apply CORS headers if the request's Origin is allowed.
 *
 * Defense-in-depth against the CORS-credentials-misconfig class of bugs:
 *
 *   • For an explicit allowlisted origin (e.g. https://claude.ai), we
 *     reflect ONLY that exact origin in `Access-Control-Allow-Origin` and
 *     emit `Vary: Origin` so caches don't cross-pollinate across origins.
 *     Pair with `Access-Control-Allow-Credentials: true` so cookies +
 *     credentialed Bearer requests work as expected.
 *
 *   • For the wildcard `*` allowlist entry, we reflect `*` literally (NOT
 *     the request's origin) and DO NOT send `Allow-Credentials: true`.
 *     Browsers reject the combo of wildcard-origin + credentials anyway,
 *     so this matches what they enforce. Equally important: it kills the
 *     CORS-credential-leak attack surface where a misconfigured wildcard
 *     could otherwise hand attacker.com a credential-bearing CORS grant.
 *
 *   • Disallowed origins get nothing — no Allow-Origin header → browser
 *     blocks the actual request even if we 200.
 *
 * Documented as a deliberate behavior split for users who pass `*`: with
 * `*` you get an unauthenticated public CORS endpoint (still bearer-gated
 * server-side, just no credentialed-cookie path). That's the right
 * trade-off.
 */
function applyCors(req: IncomingMessage, res: ServerResponse, allowOrigins: string[]): void {
  const requestOrigin = req.headers.origin;
  if (typeof requestOrigin !== "string") return;
  // Sourcing the response value from `allowOrigins` (a server-controlled
  // CLI flag) instead of from `req.headers.origin` (an attacker-controlled
  // request header) is a deliberate defense against the CORS-credential-
  // leak class of bug. CodeQL's `js/cors-misconfiguration-for-credentials`
  // query is satisfied because `matchedOrigin`'s data source is the
  // allowlist, not the request — even though the strings are equal by
  // construction at this point, the data-flow taint is what matters.
  const matchedOrigin = allowOrigins.find((o) => o === requestOrigin);
  const wildcardAllowed = matchedOrigin === undefined && allowOrigins.includes("*");
  if (matchedOrigin === undefined && !wildcardAllowed) return;
  // Wildcard branch: reflect literal "*" + OMIT Allow-Credentials (the
  // browser would reject the combo anyway, and we don't grant attacker
  // origins a credentialed window). Exact-match branch: use the trusted
  // allowlist value + send Allow-Credentials: true so cookies + Bearer
  // requests work cross-origin.
  if (wildcardAllowed) {
    res.setHeader("Access-Control-Allow-Origin", "*");
  } else if (matchedOrigin !== undefined) {
    res.setHeader("Access-Control-Allow-Origin", matchedOrigin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
  }
  res.setHeader("Vary", "Origin");
  res.setHeader("Access-Control-Allow-Methods", "POST, GET, DELETE, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Authorization, Content-Type, Mcp-Session-Id, Last-Event-ID");
  res.setHeader("Access-Control-Max-Age", "600");
}

/**
 * Build the request handler. Factored out of the listener-creation path
 * so tests can drive it without binding a TCP port.
 */
export function createHttpHandler(
  deps: ServerDeps,
  opts: HttpServeOptions
): (req: IncomingMessage, res: ServerResponse) => Promise<void> {
  const mcpPath = opts.mcpPath ?? "/mcp";
  const healthPath = opts.healthPath ?? "/health";
  const corsOrigins = opts.corsOrigins ?? [];
  const limiter = new RateLimiter(opts.rateLimitPerMinute ?? 120);
  const maxBodyBytes = 4 * 1024 * 1024; // 4MB — generous for tools/list with 36 tools

  return async (req, res) => {
    try {
      applyCors(req, res, corsOrigins);

      // OPTIONS preflight short-circuit.
      if (req.method === "OPTIONS") {
        res.statusCode = 204;
        res.end();
        return;
      }

      const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);

      // Health probe — unauthenticated, no rate-limit. Useful for
      // Tailscale/Cloudflare healthchecks. Returns just `ok` so it
      // doesn't leak version info to unauth callers.
      if (url.pathname === healthPath && req.method === "GET") {
        res.statusCode = 200;
        res.setHeader("Content-Type", "text/plain");
        res.end("ok");
        return;
      }

      if (url.pathname !== mcpPath) {
        res.statusCode = 404;
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "not found", path: url.pathname }));
        return;
      }

      // Auth: bearer token required for /mcp.
      const authHeader = req.headers.authorization;
      const tokenKey = verifyBearer(typeof authHeader === "string" ? authHeader : undefined, opts.bearerToken);
      if (tokenKey === null) {
        res.statusCode = 401;
        res.setHeader("WWW-Authenticate", 'Bearer realm="enquire-mcp"');
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "unauthorized" }));
        return;
      }

      // Rate-limit per token.
      if (!limiter.consume(tokenKey)) {
        res.statusCode = 429;
        res.setHeader("Retry-After", "60");
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "rate limit exceeded" }));
        return;
      }

      // Method gating. POST is the main MCP entry; GET is for SSE
      // streams (we're stateless, so we don't expose a long-lived GET
      // — stub it with 405); DELETE is for stateful session termination
      // (also 405 in stateless mode).
      if (req.method !== "POST") {
        sendJsonRpcError(res, 405, -32000, `Method ${req.method} not allowed for ${mcpPath}`);
        return;
      }

      let body: unknown;
      try {
        body = await readJsonBody(req, maxBodyBytes);
      } catch (err) {
        sendJsonRpcError(res, 400, -32700, err instanceof Error ? err.message : "Parse error");
        return;
      }

      // Build a fresh McpServer + transport for this request. The
      // McpServer registers tool handlers (closures over the SHARED
      // deps.vault / deps.ftsIndex), so this is cheap — no SQLite open,
      // no embedder load. The transport handles a single request and
      // closes.
      const server = buildMcpServer(deps, opts);
      const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
      try {
        await server.connect(transport);
        // Wire up cleanup so we never leak a transport on early
        // client-disconnect. Both server and transport are per-request
        // disposable — `server.close()` releases the connection, the
        // transport's `close()` flushes any pending stream.
        const cleanup = () => {
          void transport.close();
          void server.close();
        };
        res.on("close", cleanup);
        await transport.handleRequest(req, res, body);
      } catch (err) {
        process.stderr.write(`enquire http: transport error — ${err instanceof Error ? err.message : String(err)}\n`);
        sendJsonRpcError(res, 500, -32603, "Internal server error");
      }
    } catch (err) {
      // Final safety net — if anything in the outer block throws (URL
      // parse, header read), don't leave the connection hung.
      process.stderr.write(
        `enquire http: handler error — ${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`
      );
      if (!res.headersSent) {
        sendJsonRpcError(res, 500, -32603, "Internal server error");
      }
    }
  };
}

/**
 * Generate a fresh 32-byte base64url bearer token. Used by the
 * `enquire-mcp gen-token` subcommand.
 */
export function generateBearerToken(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Bind and start the HTTP transport. Returns the underlying http.Server
 * so callers (tests + CLI) can listen for `listening` / close it.
 */
export async function startHttpServer(opts: HttpServeOptions): Promise<HttpServer> {
  if (!opts.bearerToken || opts.bearerToken.length < 16) {
    throw new Error(
      "enquire serve-http: --bearer-token is required and must be ≥16 chars. " +
        "Generate one with: enquire-mcp gen-token"
    );
  }
  const deps = await prepareServerDeps(opts);
  const handler = createHttpHandler(deps, opts);
  const httpServer = createServer((req, res) => {
    void handler(req, res);
  });

  // Persistent-cache flush + watcher cleanup on signal. Same hooks as
  // stdio mode — the deps own the lifecycle. Skipped under
  // installSignalHandlers=false so tests can spawn many servers in one
  // process without accumulating SIGINT/SIGTERM listeners.
  if (opts.installSignalHandlers !== false) {
    if (deps.vault.persistentCacheEnabled) {
      let saving = false;
      let saved = false;
      const flush = async () => {
        if (saving || saved) return;
        saving = true;
        try {
          await deps.vault.saveDiskCache();
          saved = true;
        } catch (err) {
          process.stderr.write(`enquire: cache flush failed — ${err instanceof Error ? err.message : String(err)}\n`);
        } finally {
          saving = false;
        }
      };
      process.once("SIGINT", () => {
        flush().finally(() => process.exit(0));
      });
      process.once("SIGTERM", () => {
        flush().finally(() => process.exit(0));
      });
      process.on("beforeExit", () => {
        if (!saved && !saving) void flush();
      });
    }
    if (deps.watcher) {
      const closeWatcher = () => void deps.watcher?.close();
      process.once("SIGINT", closeWatcher);
      process.once("SIGTERM", closeWatcher);
      process.on("beforeExit", closeWatcher);
    }
    if (deps.ftsIndex) {
      const closeFts = () => deps.ftsIndex?.close();
      process.once("SIGINT", closeFts);
      process.once("SIGTERM", closeFts);
      process.on("beforeExit", closeFts);
    }
    // Graceful HTTP-server shutdown on signal.
    const shutdown = () => {
      httpServer.close(() => {
        // Cascade-close happens via beforeExit hooks.
      });
    };
    process.once("SIGINT", shutdown);
    process.once("SIGTERM", shutdown);
  }

  await new Promise<void>((resolve, reject) => {
    httpServer.once("error", reject);
    httpServer.listen(opts.port, opts.host, () => {
      httpServer.removeListener("error", reject);
      resolve();
    });
  });

  const addr = httpServer.address();
  const bound =
    addr && typeof addr === "object"
      ? `http://${addr.address === "::" ? "::" : addr.address}:${addr.port}`
      : `http://${opts.host}:${opts.port}`;
  const corsLabel = (opts.corsOrigins?.length ?? 0) > 0 ? `, cors=${opts.corsOrigins?.length ?? 0}` : "";
  const rateLabel = (opts.rateLimitPerMinute ?? 120) > 0 ? `, rate-limit=${opts.rateLimitPerMinute ?? 120}/min` : "";
  process.stderr.write(
    `${formatReadyBanner(deps)} (transport=http, bound=${bound}${opts.mcpPath ?? "/mcp"}${corsLabel}${rateLabel})\n`
  );
  return httpServer;
}

// Re-export the rate limiter and helpers for tests.
export { RateLimiter, readJsonBody, verifyBearer };
