// HTTP transport for enquire-mcp.
//
// v2.6.0 — remote-MCP support. Runs the MCP server over Streamable HTTP
// (the protocol claude.ai web, ChatGPT, mobile clients, and Cursor's HTTP
// mode all use). Four layers in front of the SDK transport:
//
//   1. Origin admission — a present Origin must exactly match an explicit
//      --cors-origin entry or the request fails with 403 before any route,
//      auth, rate, body, or MCP work. Missing Origin is accepted for native
//      MCP clients. Wildcard and opaque origins are rejected at startup.
//   2. Bearer auth — constant-time token compare, fail-closed (401 on
//      missing/wrong header). Token is generated by the user (we never
//      mint tokens — this is not OAuth) and passed via --bearer-token or
//      --bearer-token-env. See docs/http-transport.md for the security
//      model and Tailscale Funnel / Cloudflare Tunnel deployment recipes.
//   3. Rate-limit — per-token sliding-window bucket, 429 on overflow.
//      In-memory; survives a single process. Default 120 req/min.
//   4. CORS response headers — an admitted explicit origin receives the
//      matching browser grant. Default empty: requests without Origin still
//      work, while every browser-originated request fails admission.
//
// Modern 2026-07-28 requests use SDK v2's strict createMcpHandler entry.
// Claim-less legacy traffic keeps the established Node streamable transport:
// stateless by default, or session-keyed behind `stateful: true`. Every leg
// builds a fresh registered McpServer over SHARED Vault/FtsIndex/EmbedDb
// handles. This is why prepareServerDeps() runs once in startHttpServer(),
// while buildMcpServer() may run per request/session: heavy I/O stays at boot.
//
// Stateless is the DEFAULT (our tools are short-running — search, read,
// frontmatter ops), and the right choice for most deployments. Stateful,
// sessionId-keyed transports shipped in v2.14.0 as an opt-in (`stateful: true`):
// a session registry keys requests by an assigned `Mcp-Session-Id`, evicts
// sessions idle past a configurable TTL, tracks `pendingInits`/`inFlight`
// refcounts to avoid mid-request teardown, and drains under a bounded graceful
// shutdown. Enable it only when a client needs sticky per-session state.

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { createServer, type Server as HttpServer, type IncomingMessage, type ServerResponse } from "node:http";
import { NodeStreamableHTTPServerTransport, toNodeHandler, toWebRequest } from "@modelcontextprotocol/node";
import { createMcpHandler, isLegacyRequest, type McpHttpHandler } from "@modelcontextprotocol/server";
import { buildMcpServer, formatReadyBanner, prepareServerDeps, type ServeOptions, type ServerDeps } from "./index.js";
import {
  createPreparedServerCleanupOwner,
  PreparedServerCleanupError,
  type PreparedServerCleanupOwner,
  retryIncompleteShutdownOnce
} from "./shutdown.js";
import { TOOL_MANIFEST } from "./tool-manifest.js";
import { DEFAULT_MAX_FILE_BYTES } from "./vault.js";
import { WriteRequestTracker } from "./write-lifecycle.js";

/** v3.11.6-rc.20 (audit H-2) — ordinary `DELETE /mcp` request-drain bound.
 *  Reads that exceed it may be cut off; persistent writes are never cut:
 *  rc.6 cancels + rolls back safe batches or lets atomic effects finish, keeps
 *  the session alive, and returns retryable 409. Process shutdown uses the
 *  same ordinary bound, followed by an integrity tail for persistent writes. */
const DELETE_DRAIN_MS = 5000;
/** Bounded grace for modern per-request exchanges before handler close aborts stragglers. */
const MODERN_DRAIN_MS = 5000;
/** Bound for the SDK handler's graceful protocol close after write integrity settles. */
const MODERN_CLOSE_MS = 3000;
/** Bound for one legacy stateful session's transport.close / server.close under closeAll. */
const LEGACY_SESSION_CLOSE_MS = 3000;
/** Minimum request budget retained for ordinary MCP envelopes. */
const MIN_HTTP_JSON_BODY_BYTES = 4 * 1024 * 1024;
/** Worst-case JSON string expansion: one decoded control byte becomes `\u00xx`. */
const HTTP_JSON_ESCAPE_EXPANSION = 6;
/** Fixed allowance for the JSON-RPC/MCP envelope around one file-sized string. */
const HTTP_JSON_ENVELOPE_HEADROOM_BYTES = 64 * 1024;
/** Process-memory safety ceiling for one buffered and parsed HTTP JSON request. */
const MAX_HTTP_JSON_BODY_BYTES = 64 * 1024 * 1024;
const PERSISTENT_WRITE_TOOLS = new Set(
  TOOL_MANIFEST.filter((tool) => tool.kind === "write" || tool.kind === "feedback").map((tool) => tool.name)
);

/**
 * Internal controls for deterministic transport and lifecycle tests.
 *
 * Production callers should omit this object. It is intentionally separate
 * from {@link HttpServeOptions} so no CLI/config surface can weaken the normal
 * five-second drain.
 *
 * @internal
 */
export interface HttpTransportInternals {
  /** Override the stateful DELETE call-drain deadline in tests. */
  deleteDrainMs?: number;
  /** Override the modern per-request shutdown grace in tests. */
  modernDrainMs?: number;
  /** Override the modern SDK-handler close bound in tests. */
  modernCloseMs?: number;
  /** Supply the modern + legacy-stateless aggregate write tracker in lifecycle tests. */
  modernWriteTracker?: WriteRequestTracker;
  /** Replace the modern handler close operation in bounded-close tests. */
  modernHandlerClose?: () => Promise<void>;
  /** Pause after a DELETE owns session admission; used only by lifecycle tests. */
  afterDeleteMarkedClosing?: (sessionId: string) => void | Promise<void>;
  /** Pause after a modern request owns an in-flight slot; used only by lifecycle tests. */
  afterModernRequestAdmitted?: () => void | Promise<void>;
  /** Pause after a stateful session occupies an in-flight slot; used only by lifecycle tests. */
  afterStatefulRequestAdmitted?: () => void | Promise<void>;
  /** Fault-injection point after listen and owner installation but before startup commits. */
  beforeStartupCommit?: (server: HttpServer, deps: ServerDeps) => void | Promise<void>;
  /** Replace TCP listener construction in ownership tests without binding an operating-system socket. */
  httpServerFactory?: (requestListener: (req: IncomingMessage, res: ServerResponse) => void) => HttpServer;
  /** Override the already-validated production JSON body cap with a small test-only limit. */
  maxBodyBytes?: number;
}

/**
 * Configuration for the HTTP transport. Extends ServeOptions so every
 * stdio-mode flag (--enable-write, --persistent-index, --watch, etc.) is
 * available over HTTP too.
 */
export interface HttpServeOptions extends ServeOptions {
  /** TCP port to listen on. Must be a safe integer in [0, 65535]; 0 requests an ephemeral port. */
  port: number;
  /**
   * Non-empty bind host with no outer whitespace. Default 127.0.0.1 —
   * explicit because remote-MCP must opt-in to bind 0.0.0.0. Most users should
   * keep it on localhost and front it with Tailscale Funnel / Cloudflare
   * Tunnel for remote access (auth-and-encryption-in-depth).
   * See docs/http-transport.md.
   */
  host: string;
  /**
   * Bearer token of at least 16 characters with no outer whitespace.
   * Comparing constant-time. Required: a missing token fails closed at startup
   * (we refuse to bind without auth). Generate
   * with: `node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))"`.
   */
  bearerToken: string;
  /**
   * Canonical absolute URL pathname for the MCP endpoint.
   * Default `/mcp`; must differ from `healthPath`.
   */
  mcpPath?: string;
  /** Max requests per minute per bearer token. Safe non-negative integer; default 120. 0 disables. */
  rateLimitPerMinute?: number;
  /**
   * Exact HTTP(S) Origin allowlist. Repeatable. Default empty: requests
   * without an Origin header work, while browser-originated requests fail
   * with 403. Wildcard `*`, opaque `null`, paths, queries and fragments are
   * rejected at startup because they cannot enforce DNS-rebinding admission.
   */
  corsOrigins?: string[];
  /**
   * Canonical absolute URL pathname for the health probe.
   * Default `/health`; must differ from `mcpPath`.
   */
  healthPath?: string;
  /**
   * v2.14.0 — when `true`, the HTTP transport runs in stateful mode:
   * sessions are keyed by the `Mcp-Session-Id` header, each session has
   * its own `McpServer` + `NodeStreamableHTTPServerTransport` pair, and
   * server-initiated notifications stream over a long-lived `GET /mcp`
   * SSE connection. Required for ChatGPT custom GPT actions and other
   * clients that expect persistent state across requests. Off by default
   * (stateless mode is the right choice for short-running tools and
   * minimizes attack surface).
   */
  stateful?: boolean;
  /**
   * v2.14.0 — when stateful, evict sessions idle longer than this many
   * milliseconds. Must be a positive safe integer. Default 30 minutes.
   * Sweep runs lazily on every request (no separate timer). Idle = time since the last
   * `handleRequest` for that session.
   */
  sessionIdleTimeoutMs?: number;
  /**
   * v2.14.0 — max concurrent sessions. New sessions beyond this cap are
   * rejected with 503 + `Retry-After`. Must be a positive safe integer.
   * Default 100; protects against
   * memory exhaustion under adversarial create-and-abandon traffic.
   */
  maxSessions?: number;
  /**
   * When `true` (default), registers SIGINT/SIGTERM/beforeExit listeners
   * for graceful shutdown of the HTTP server, vault, FTS5 index, watcher,
   * and persistent cache. Tests pass `false` to avoid leaking listeners
   * when spawning many `startHttpServer()` instances in one process —
   * cleanup happens via `httpServer.close()` which still triggers the
   * underlying resource cleanup.
   */
  installSignalHandlers?: boolean;
}

const MAX_HTTP_PORT = 65_535;
const MAX_HTTP_INTEGER = Number.MAX_SAFE_INTEGER;
const HTTP_ROUTE_BASE = new URL("http://enquire.invalid");
const HTTP_BOOLEAN_OPTIONS = [
  "stateful",
  "installSignalHandlers"
] as const satisfies readonly (keyof HttpServeOptions)[];

function assertHttpInteger(
  value: unknown,
  name: "port" | "rateLimitPerMinute" | "sessionIdleTimeoutMs" | "maxSessions",
  minimum: number,
  maximum: number
): asserts value is number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < minimum || value > maximum) {
    throw new TypeError(`HTTP serve option ${name} must be a safe integer in [${minimum}, ${maximum}]`);
  }
}

function normalizeHttpRoutePath(value: unknown, name: "mcpPath" | "healthPath"): string {
  if (typeof value !== "string") {
    throw new TypeError(`HTTP serve option ${name} must be a string`);
  }
  let parsed: URL;
  try {
    parsed = new URL(value, HTTP_ROUTE_BASE);
  } catch {
    throw new TypeError(`HTTP serve option ${name} must be a canonical absolute pathname`);
  }
  if (
    !value.startsWith("/") ||
    value.startsWith("//") ||
    value.includes("?") ||
    value.includes("#") ||
    /%(?![0-9a-fA-F]{2})/.test(value) ||
    parsed.origin !== HTTP_ROUTE_BASE.origin ||
    parsed.pathname !== value ||
    parsed.search !== "" ||
    parsed.hash !== ""
  ) {
    throw new TypeError(`HTTP serve option ${name} must be a canonical absolute pathname without query or fragment`);
  }
  return value;
}

/**
 * Validate and normalize the public HTTP transport configuration without
 * coercing caller-controlled values. This boundary is dependency-free so both
 * direct handler construction and listener startup reject invalid transport
 * options before touching server dependencies, request bodies, or sockets.
 *
 * Inherited {@link ServeOptions} fields are validated by the server layer,
 * except `maxFileBytes`: its HTTP wire-budget coupling is admitted here so an
 * impossible body cap fails before vault/index preparation or socket listen.
 *
 * @param value - Untrusted programmatic HTTP serve configuration.
 * @returns A shallow copy with default route paths and normalized CORS origins.
 * @throws {TypeError} When an HTTP option has the wrong runtime type or domain.
 * @throws {RangeError} When `maxFileBytes` cannot fit the bounded HTTP representation.
 * @example
 * ```ts
 * const opts = normalizeHttpServeOptions({
 *   vault: "/notes",
 *   port: 3000,
 *   host: "127.0.0.1",
 *   bearerToken: "replace-with-a-secret"
 * });
 * ```
 */
export function normalizeHttpServeOptions(value: unknown): HttpServeOptions {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError("HTTP serve options must be an object");
  }
  const opts = value as Record<string, unknown>;

  assertHttpInteger(opts.port, "port", 0, MAX_HTTP_PORT);
  for (const name of ["host", "bearerToken"] as const) {
    if (typeof opts[name] !== "string") {
      throw new TypeError(`HTTP serve option ${name} must be a string`);
    }
  }
  const host = opts.host as string;
  if (host.length === 0 || host.trim() !== host) {
    throw new TypeError("HTTP serve option host must be non-empty and contain no outer whitespace");
  }
  const bearerToken = opts.bearerToken as string;
  if (bearerToken.length < 16 || bearerToken.trim() !== bearerToken) {
    throw new TypeError(
      "enquire serve-http: --bearer-token is required, must be ≥16 chars, and contain no outer whitespace. " +
        "Generate one with: enquire-mcp gen-token"
    );
  }

  for (const name of HTTP_BOOLEAN_OPTIONS) {
    const option = opts[name];
    if (option !== undefined && typeof option !== "boolean") {
      throw new TypeError(`HTTP serve option ${name} must be a boolean`);
    }
  }
  if (
    opts.corsOrigins !== undefined &&
    (!Array.isArray(opts.corsOrigins) || !opts.corsOrigins.every((origin) => typeof origin === "string"))
  ) {
    throw new TypeError("HTTP serve option corsOrigins must be an array of strings");
  }
  if (opts.rateLimitPerMinute !== undefined) {
    assertHttpInteger(opts.rateLimitPerMinute, "rateLimitPerMinute", 0, MAX_HTTP_INTEGER);
  }
  if (opts.sessionIdleTimeoutMs !== undefined) {
    assertHttpInteger(opts.sessionIdleTimeoutMs, "sessionIdleTimeoutMs", 1, MAX_HTTP_INTEGER);
  }
  if (opts.maxSessions !== undefined) {
    assertHttpInteger(opts.maxSessions, "maxSessions", 1, MAX_HTTP_INTEGER);
  }
  if (opts.maxFileBytes !== undefined && typeof opts.maxFileBytes !== "string") {
    throw new TypeError("HTTP serve option maxFileBytes must be a string");
  }
  deriveHttpBodyCap(opts.maxFileBytes as string | undefined);

  const mcpPath = normalizeHttpRoutePath(opts.mcpPath === undefined ? "/mcp" : opts.mcpPath, "mcpPath");
  const healthPath = normalizeHttpRoutePath(opts.healthPath === undefined ? "/health" : opts.healthPath, "healthPath");
  if (mcpPath === healthPath) {
    throw new TypeError("HTTP serve options mcpPath and healthPath must be distinct");
  }

  return {
    ...(value as HttpServeOptions),
    mcpPath,
    healthPath,
    corsOrigins: normalizeCorsOrigins(opts.corsOrigins as string[] | undefined)
  };
}

/**
 * Sliding-window rate limiter. Per-token. Window is rolling 60 seconds.
 * Uses a tiny circular buffer of timestamps per token — O(burst-size)
 * memory per token, no GC churn (we trim when we check).
 *
 * NOT distributed. If the user runs multiple processes behind a load
 * balancer they'd want a shared store (Redis); deferred to v2.7+.
 */
class RateLimiter {
  private readonly perMinute: number;
  private readonly windows = new Map<string, number[]>();

  constructor(perMinute: number) {
    this.perMinute = perMinute;
  }

  /** Returns true if request allowed; false if over budget. */
  consume(tokenId: string, nowMs: number = Date.now()): boolean {
    if (this.perMinute <= 0) return true; // disabled
    const cutoff = nowMs - 60_000;
    let timestamps = this.windows.get(tokenId);
    if (!timestamps) {
      timestamps = [];
      this.windows.set(tokenId, timestamps);
    }
    // Trim out-of-window entries from the front (they're append-ordered).
    while (timestamps.length > 0 && (timestamps[0] ?? 0) < cutoff) {
      timestamps.shift();
    }
    if (timestamps.length >= this.perMinute) return false;
    timestamps.push(nowMs);
    return true;
  }

  /** Test-only: reset all windows. */
  reset(): void {
    this.windows.clear();
  }
}

/**
 * Constant-time bearer-token compare. The Authorization header is
 * `Bearer <token>` per RFC 6750. We compare against the raw token
 * supplied at startup — both sides padded to a hash so timingSafeEqual
 * doesn't leak length.
 *
 * Returns the SHA-256 digest of the token (used as the rate-limit key)
 * if valid, or null if not. We never use the raw token as the key — a
 * compromised log dump would expose it.
 */
function verifyBearer(authHeader: string | undefined, expectedToken: string): string | null {
  if (!authHeader?.startsWith("Bearer ")) return null;
  const presented = authHeader.slice("Bearer ".length).trim();
  if (presented.length === 0) return null;
  // Hash both sides so timingSafeEqual gets equal-length buffers regardless
  // of whether the presented token is longer or shorter than expected. The
  // hash is constant-length, so length-comparison short-circuits don't leak.
  const expectedHash = createHash("sha256").update(expectedToken).digest();
  const presentedHash = createHash("sha256").update(presented).digest();
  if (!timingSafeEqual(expectedHash, presentedHash)) return null;
  // Return the digest as the rate-limit key. Different tokens produce
  // different keys; the same token always produces the same key.
  return presentedHash.toString("hex").slice(0, 16);
}

/**
 * Normalize and validate the configured browser Origin allowlist.
 *
 * The MCP Streamable HTTP security contract requires a present invalid Origin
 * to fail before request handling. Exact serialized HTTP(S) origins are the
 * only configuration that can support that decision without trusting the
 * attacker-controlled Host header. Wildcard, opaque and URL-with-path forms
 * therefore fail at startup instead of silently weakening the boundary.
 *
 * @param origins - Configured `--cors-origin` values.
 * @returns A de-duplicated list of exact serialized origins.
 * @throws TypeError when any entry is not a safe exact HTTP(S) origin.
 * @internal
 */
export function normalizeCorsOrigins(origins: readonly string[] = []): string[] {
  const normalized = new Set<string>();
  for (const origin of origins) {
    if (origin === "*" || origin === "null") {
      throw new TypeError(
        `enquire serve-http: --cors-origin ${JSON.stringify(origin)} is unsafe; list each exact HTTP(S) origin`
      );
    }
    if (origin.trim() !== origin || origin.length === 0) {
      throw new TypeError(
        "enquire serve-http: --cors-origin entries must be non-empty and contain no outer whitespace"
      );
    }
    let parsed: URL;
    try {
      parsed = new URL(origin);
    } catch {
      throw new TypeError(
        `enquire serve-http: invalid --cors-origin ${JSON.stringify(origin)}; expected an exact HTTP(S) origin`
      );
    }
    if ((parsed.protocol !== "http:" && parsed.protocol !== "https:") || parsed.origin !== origin) {
      throw new TypeError(
        `enquire serve-http: invalid --cors-origin ${JSON.stringify(origin)}; use only scheme + host + optional port`
      );
    }
    normalized.add(origin);
  }
  return [...normalized];
}

/**
 * Decide whether an incoming request passes the MCP Origin admission boundary.
 *
 * Native/non-browser MCP clients normally omit Origin and remain compatible.
 * A present value must exactly match the validated allowlist; opaque `null`,
 * malformed, duplicated/comma-joined and unlisted values therefore fail.
 *
 * @param requestOrigin - Incoming `Origin` header, if present.
 * @param allowOrigins - Validated exact Origin allowlist.
 * @returns `true` only when the request may proceed.
 * @internal
 */
export function isRequestOriginAllowed(requestOrigin: string | undefined, allowOrigins: readonly string[]): boolean {
  return requestOrigin === undefined || allowOrigins.includes(requestOrigin);
}

/**
 * Parse the media-type essence needed by MCP POST admission.
 *
 * SDK v2 requires `application/json`; parameters and case variants are
 * accepted, while missing, joined/duplicated, or misleading parameter values
 * are rejected. This guard runs before JSON parsing so invalid media types
 * deterministically receive 415 rather than a parse error or legacy fallback.
 *
 * @param value - Node's incoming `Content-Type` header value.
 * @returns Whether the header unambiguously denotes `application/json`.
 * @internal
 */
export function isJsonContentType(value: string | string[] | undefined): boolean {
  if (typeof value !== "string" || value.length === 0) return false;
  const separator = value.indexOf(";");
  const essence = (separator === -1 ? value : value.slice(0, separator)).trim().toLowerCase();
  const parameters = separator === -1 ? "" : value.slice(separator + 1);
  // Node coalesces duplicate headers with a top-level comma. RFC parameters
  // may legally contain commas inside quoted strings, including escaped
  // quotes, so distinguish those from a joined second media type. If a quoted
  // string is malformed/unclosed, match SDK v2's fallback: accept the JSON
  // essence unless that ambiguous tail itself contained a comma.
  let quoted = false;
  let escaped = false;
  let quotedComma = false;
  for (const char of parameters) {
    if (escaped) {
      escaped = false;
      continue;
    }
    if (quoted && char === "\\") {
      escaped = true;
      continue;
    }
    if (char === '"') {
      quoted = !quoted;
      continue;
    }
    if (char === ",") {
      if (!quoted) return false;
      quotedComma = true;
    }
  }
  return essence === "application/json" && !(quoted && quotedComma);
}

/**
 * Typed signal that the declared or streamed request body exceeded its admitted
 * byte budget. The HTTP boundary maps this type to a generic 413 response while
 * ordinary JSON syntax failures remain 400 parse errors.
 *
 * @example
 * ```ts
 * throw new BodyTooLargeError();
 * ```
 * @internal
 */
export class BodyTooLargeError extends Error {
  constructor() {
    super("HTTP request body exceeds its admitted byte budget");
    this.name = "BodyTooLargeError";
  }
}

function declaredContentLengthExceeds(req: IncomingMessage, maxBytes: number): boolean {
  const raw = req.headers?.["content-length"];
  if (typeof raw !== "string" || !/^[0-9]+$/u.test(raw)) return false;
  const normalized = raw.replace(/^0+/u, "") || "0";
  const maximum = String(maxBytes);
  return normalized.length > maximum.length || (normalized.length === maximum.length && normalized > maximum);
}

/**
 * Read and parse one bounded UTF-8 JSON request body.
 *
 * A valid numeric `Content-Length` is rejected before stream consumption when
 * it exceeds the cap. Chunked bodies and under-declared bodies remain protected
 * by the incremental byte counter.
 *
 * @param req - Incoming Node request stream.
 * @param maxBytes - Positive safe-integer wire-byte budget.
 * @returns Parsed JSON, or `undefined` for an empty body.
 * @throws {BodyTooLargeError} If declared or observed bytes exceed `maxBytes`.
 * @throws {SyntaxError} If the admitted non-empty body is not valid JSON.
 * @internal
 */
async function readJsonBody(req: IncomingMessage, maxBytes: number): Promise<unknown> {
  if (!Number.isSafeInteger(maxBytes) || maxBytes < 1 || maxBytes > MAX_HTTP_JSON_BODY_BYTES) {
    throw new TypeError(`HTTP JSON body cap must be a safe integer in [1, ${MAX_HTTP_JSON_BODY_BYTES}]`);
  }
  if (declaredContentLengthExceeds(req, maxBytes)) throw new BodyTooLargeError();
  const chunks: Buffer[] = [];
  let total = 0;
  for await (const chunk of req) {
    const buf = Buffer.from(chunk);
    total += buf.length;
    if (total > maxBytes) {
      throw new BodyTooLargeError();
    }
    chunks.push(buf);
  }
  if (total === 0) return undefined;
  const text = Buffer.concat(chunks).toString("utf8");
  return JSON.parse(text);
}

/**
 * v3.7.13 H2 — detect a JSON-RPC 2.0 `initialize` request without parsing
 * the full envelope. The body can be either a single message or a batch
 * (JSON-RPC permits arrays); we accept both, requiring AT LEAST ONE
 * element in a batch to be `method: "initialize"`. Returns false on
 * anything else (including malformed bodies — the caller has already
 * parsed JSON, so the shape is unknown but not parse-error territory).
 *
 * @internal — exported only for tests.
 */
export function isInitializeRequest(body: unknown): boolean {
  if (Array.isArray(body)) return body.some(isInitializeRequest);
  if (!body || typeof body !== "object") return false;
  const method = (body as { method?: unknown }).method;
  return method === "initialize";
}

/**
 * Return true when a JSON-RPC body contains at least one persistent MCP tool
 * mutation. Handles both single messages and protocol batches.
 *
 * Derived from {@link TOOL_MANIFEST}, so a newly registered vault-write or
 * feedback tool joins the lifecycle counter without a second hand-maintained
 * name list.
 *
 * @param body - Parsed JSON-RPC request body.
 * @returns Whether the request can mutate vault or feedback persistence.
 * @internal
 */
export function isPersistentWriteRequest(body: unknown): boolean {
  if (Array.isArray(body)) return body.some(isPersistentWriteRequest);
  if (!body || typeof body !== "object") return false;
  const message = body as { method?: unknown; params?: { name?: unknown } };
  return (
    message.method === "tools/call" &&
    typeof message.params?.name === "string" &&
    PERSISTENT_WRITE_TOOLS.has(message.params.name)
  );
}

/** Send a JSON-RPC error response with the given HTTP + RPC status. */
function sendJsonRpcError(res: ServerResponse, httpStatus: number, code: number, message: string): void {
  if (res.headersSent) return;
  res.statusCode = httpStatus;
  res.setHeader("Content-Type", "application/json");
  res.end(
    JSON.stringify({
      jsonrpc: "2.0",
      error: { code, message },
      id: null
    })
  );
}

/**
 * Apply browser CORS response headers after Origin admission succeeds.
 *
 * The response value comes only from the validated server-controlled
 * allowlist. `Vary: Origin` prevents cache cross-pollination and
 * Allow-Credentials supports credentialed browser clients. Rejected origins
 * never reach this function; omission of a response header is not treated as
 * request admission.
 */
function applyCors(req: IncomingMessage, res: ServerResponse, allowOrigins: string[]): void {
  const requestOrigin = req.headers.origin;
  if (typeof requestOrigin !== "string") return;
  // Sourcing the response value from `allowOrigins` (a server-controlled
  // CLI flag) instead of from `req.headers.origin` (an attacker-controlled
  // request header) is a deliberate defense against the CORS-credential-
  // leak class of bug. CodeQL's `js/cors-misconfiguration-for-credentials`
  // query is satisfied because `matchedOrigin`'s data source is the
  // allowlist, not the request — even though the strings are equal by
  // construction at this point, the data-flow taint is what matters.
  const matchedOrigin = allowOrigins.find((o) => o === requestOrigin);
  if (matchedOrigin === undefined) return;
  res.setHeader("Access-Control-Allow-Origin", matchedOrigin);
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Vary", "Origin");
  res.setHeader("Access-Control-Allow-Methods", "POST, GET, DELETE, OPTIONS");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Authorization, Content-Type, Mcp-Session-Id, Last-Event-ID, MCP-Protocol-Version, Mcp-Method, Mcp-Name"
  );
  // v3.10.0-rc.62 (HTTP-CORS-EXPOSE-SESSION-ID) — `Access-Control-Allow-Headers` only lets a
  // browser SEND `Mcp-Session-Id` on the request; to let cross-origin JS READ the session id the
  // server returns on `initialize`, it must be listed in `Access-Control-Expose-Headers`. Without
  // this, a browser MCP client in stateful mode cannot capture the `Mcp-Session-Id` response header
  // and every follow-up request is treated as a new session (the SDK exposes it as a response header).
  res.setHeader(
    "Access-Control-Expose-Headers",
    "Mcp-Session-Id, WWW-Authenticate, Last-Event-ID, MCP-Protocol-Version"
  );
  res.setHeader("Access-Control-Max-Age", "600");
}

/**
 * Build the request handler. Factored out of the listener-creation path
 * so tests can drive it without binding a TCP port.
 */
/**
 * v2.14.0 — one entry in the stateful-session map. Each session pairs an
 * `McpServer` instance with a `NodeStreamableHTTPServerTransport` (in
 * stateful mode the SDK keys requests by the session id we assign at
 * `initialize` time) and tracks the last activity timestamp for
 * idle-eviction.
 *
 * v3.8.7 P2-10 — added `inFlight` refcount + `closing` flag to make
 * session lifecycle safe under concurrent requests:
 *   - `inFlight > 0` means at least one HTTP handler is currently
 *     awaiting `transport.handleRequest` on this session. The idle sweep
 *     skips such sessions even if their `lastActivityMs` is past the
 *     cutoff — closing a transport with an in-flight SSE/POST mid-stream
 *     produces broken responses and dangling McpServer state.
 *   - `closing` is set by the explicit shutdown paths (DELETE + sweep +
 *     `closeAll`) right before we begin teardown. Once true, the entry
 *     is also removed from `registry.sessions` so new gets return 404 —
 *     concurrent requests that already hold a `session` reference can
 *     finish naturally but won't be joined by new ones.
 */
interface StatefulSession {
  server: ReturnType<typeof buildMcpServer>;
  transport: InstanceType<typeof NodeStreamableHTTPServerTransport>;
  /** Epoch-ms of the last completed `handleRequest` occupancy for this session. */
  lastActivityMs: number;
  /**
   * v3.8.7 — count of ALL handlers currently inside `transport.handleRequest`
   * for this session (POST tool calls, the initialize handler, AND the
   * long-lived GET SSE stream). Incremented by `runWithRefcount`. `sweepIdle`
   * waits for this to be 0 before evicting — so a session with an open SSE
   * notification stream is never idle-evicted (it's an active client).
   */
  inFlight: number;
  /**
   * v3.11.6-rc.21 (rc.20 re-sweep F1) — count of DRAINABLE requests only: POST
   * tool calls + the initialize handler, i.e. the requests whose responses /
   * mutations must be allowed to COMPLETE before teardown. Deliberately EXCLUDES
   * the long-lived GET SSE stream, which `handleRequest` keeps pending for the
   * entire stream lifetime (it resolves only when the stream ends). DELETE +
   * `closeAll` drain THIS counter, not `inFlight` — draining `inFlight` (rc.20)
   * made every clean DELETE with an open SSE block the full `DELETE_DRAIN_MS`
   * (the SSE never self-completes; the DELETE is precisely what terminates it),
   * a 5s regression on the flagship stateful path. Draining `inFlightCalls`
   * instead lets the DELETE tear the SSE down immediately while still waiting
   * for a genuine in-flight tool call.
   */
  inFlightCalls: number;
  /**
   * POST requests whose response belongs to a persistent mutation. This stays
   * positive through SDK response delivery, covering the interval after the
   * write callback settles but before `transport.handleRequest` returns.
   */
  inFlightWrites?: number;
  /**
   * Per-session persistent-mutation registry. Real stateful sessions always
   * provide it; optional keeps direct registry fixtures backwards compatible.
   */
  writeTracker?: WriteRequestTracker;
  /**
   * DELETE timed out on a persistent request. Keep the session unavailable
   * until every such HTTP response drains, then atomically re-open it.
   */
  resumeAfterWrites?: boolean;
  /**
   * v3.8.7 — once set, the session is being torn down. The entry has
   * already been removed from `registry.sessions`; new requests will
   * 404. Existing in-flight requests are allowed to finish.
   */
  closing: boolean;
}

/**
 * v2.14.0 — exported for tests so they can poke at the session map
 * directly (idle eviction, max-cap, etc.) without spinning up a real
 * HTTP server.
 *
 * v3.8.7 P2-10/P2-11 — extended:
 *   - `pendingInits` makes the maxSessions cap-check atomic across
 *     concurrent initialize POSTs. The check is now
 *     `sessions.size + pendingInits >= maxSessions`. Each init handler
 *     increments before allocating server+transport and decrements in a
 *     finally. Without this, N concurrent inits could all pass the
 *     plain `size()` check and create N+ sessions.
 *   - v3.11.7-rc.1: `acceptingInits` closes synchronously before shutdown
 *     drains `pendingInits`, and `registerSession` refuses a session that
 *     completes after the bound. Without the gate, `closeAll` could snapshot
 *     an empty map and return while an already-reserved initialize inserted a
 *     brand-new live session afterwards.
 *   - `closeAll(timeoutMs)` is the graceful-shutdown drain: waits for
 *     ordinary in-flight requests up to `timeoutMs`, then cancels + rolls back
 *     safe batch writes and waits for every remaining persistent mutation
 *     before closing each transport + McpServer pair. Used by
 *     `shutdownHttpServer` so tests + production both leave a clean process
 *     state (no leaked SQLite handles via per-session hooks).
 */
export interface SessionRegistry {
  readonly sessions: Map<string, StatefulSession>;
  /** Sweep idle sessions older than `idleTimeoutMs`. Returns evicted count. */
  sweepIdle(nowMs?: number): number;
  /** Total sessions currently tracked. */
  size(): number;
  /**
   * v3.8.7 — count of in-flight `initialize` POSTs that have passed the
   * cap-check but not yet been inserted into `sessions`. Used by the
   * cap-check to prevent the TOCTOU race where N concurrent inits all
   * see `size() < maxSessions` and overshoot. Public so tests can
   * assert it stays balanced (always returns to 0 after init resolves).
   */
  readonly pendingInits: number;
  /** False once graceful shutdown starts; never becomes true again. */
  readonly acceptingInits: boolean;
  /** Atomically reserve an initialize slot unless shutdown has closed the gate. */
  tryReserveInit(): boolean;
  /** Release one successful `tryReserveInit` reservation. */
  releaseInit(): void;
  /** Publish a completed session only while the initialize gate is open. */
  registerSession(sid: string, session: StatefulSession): boolean;
  /**
   * Graceful drain: mark all sessions as `closing`, wait up to `timeoutMs`
   * for ordinary in-flight requests, then preserve persistent-write integrity
   * through rollback/finish before bounding every transport + McpServer close.
   * Returns the number of sessions closed. Idempotent.
   */
  closeAll(timeoutMs?: number): Promise<number>;
}

export function createSessionRegistry(
  idleTimeoutMs: number,
  protocolCloseMs: number = LEGACY_SESSION_CLOSE_MS
): SessionRegistry {
  const sessions = new Map<string, StatefulSession>();
  let pendingInits = 0;
  let acceptingInits = true;
  const registry: SessionRegistry = {
    sessions,
    get pendingInits(): number {
      return pendingInits;
    },
    get acceptingInits(): boolean {
      return acceptingInits;
    },
    tryReserveInit(): boolean {
      if (!acceptingInits) return false;
      pendingInits += 1;
      return true;
    },
    releaseInit(): void {
      if (pendingInits <= 0) {
        throw new Error("SessionRegistry invariant violated: releaseInit without a reservation");
      }
      pendingInits -= 1;
    },
    registerSession(sid, session): boolean {
      if (!acceptingInits) {
        session.closing = true;
        return false;
      }
      sessions.set(sid, session);
      return true;
    },
    sweepIdle(nowMs = Date.now()): number {
      const cutoff = nowMs - idleTimeoutMs;
      let evicted = 0;
      for (const [sid, session] of sessions) {
        if (session.closing) continue; // already being torn down
        // v3.8.7 P2-10 — skip in-flight sessions. Closing a transport
        // while a handler is awaiting handleRequest on it leaves the
        // response stream in an inconsistent state (the SDK's internal
        // queue still expects to drain). Next sweep will catch it once
        // the in-flight request finishes.
        if (session.inFlight > 0) continue;
        if (session.lastActivityMs < cutoff) {
          session.closing = true;
          sessions.delete(sid);
          // Best-effort cleanup — don't block on slow close.
          void session.transport.close().catch(() => {});
          void session.server.close().catch(() => {});
          evicted += 1;
        }
      }
      return evicted;
    },
    size: () => sessions.size,
    async closeAll(timeoutMs = 5000): Promise<number> {
      // v3.11.7-rc.1 (A11) — close the initialize gate AND remove every
      // already-live session synchronously. Existing-session requests now
      // bounce with 404 while already-reserved init bodies + in-flight calls
      // drain. Any init that had not registered before this point is refused
      // by registerSession and self-closes in the handler; it can never appear
      // after our snapshot.
      acceptingInits = false;
      const snapshot = Array.from(sessions.values());
      for (const s of snapshot) {
        s.closing = true;
        s.resumeAfterWrites = false;
        s.writeTracker?.closeAdmission();
      }
      sessions.clear();
      const deadline = Date.now() + Math.max(0, timeoutMs);
      // One shared bound covers both pending initialize bodies and in-flight
      // calls. Do NOT wait on long-lived GET SSE streams: teardown terminates
      // them, while pending init + POST calls need a chance to complete.
      while (Date.now() < deadline) {
        if (pendingInits === 0 && snapshot.every((s) => s.inFlightCalls === 0)) break;
        await new Promise<void>((resolve) => setTimeout(resolve, 10));
      }
      // A bounded ordinary drain may expire while a persistent mutation is
      // still active. Rollback-capable batches receive explicit cancellation;
      // atomic/single-effect writes finish under the shared write lane. This
      // integrity tail may extend shutdown beyond `timeoutMs`, but teardown
      // never closes a response channel while a tool can still mutate disk.
      for (const s of snapshot) {
        if (!s.writeTracker) continue;
        await s.writeTracker.abortRollbackSafe("Server shutdown exceeded the request-drain deadline");
        await s.writeTracker.waitForAll();
      }
      // Close everything regardless — best-effort. After timeoutMs an
      // in-flight READ handler may be stuck and we'd rather hand back the port
      // than wait forever. Persistent mutations have completed or rolled back.
      // Protocol close is bounded: a hung SDK close must not pin shutdown
      // ahead of TCP force-close.
      await Promise.all(
        snapshot.map(async (s) => {
          await Promise.all([
            waitForBoundedSettlement(
              Promise.resolve()
                .then(() => s.transport.close())
                .catch(() => {}),
              protocolCloseMs
            ),
            waitForBoundedSettlement(
              Promise.resolve()
                .then(() => s.server.close())
                .catch(() => {}),
              protocolCloseMs
            )
          ]);
        })
      );
      return snapshot.length;
    }
  };
  return registry;
}

class SessionRegistryClosingError extends Error {
  constructor() {
    super("Stateful session registry is shutting down");
    this.name = "SessionRegistryClosingError";
  }
}

/**
 * v3.8.7 P2-10 — wrap a `handleRequest` call with the in-flight refcount.
 * The increment is synchronous (no `await` between increment + the work
 * starting), so the idle sweep can never see `inFlight === 0` while a
 * handler is mid-flight. The decrement runs in a `finally` so it fires
 * on both success + rejection paths. `isWrite` additionally holds
 * `inFlightWrites` through SDK response delivery, so DELETE cannot miss a
 * write whose callback settled just before `handleRequest` returns.
 *
 * v3.11.6-rc.21 (rc.20 re-sweep F1) — `isCall` distinguishes a DRAINABLE request
 * (a POST tool call / initialize, which must be allowed to complete before
 * teardown — the default) from the long-lived GET SSE stream (`isCall: false`),
 * which teardown TERMINATES rather than waits for. Both bump `inFlight` (so
 * idle-sweep sees the session as active); only calls bump `inFlightCalls` (what
 * DELETE / closeAll drain on).
 */
async function runWithRefcount<T>(
  session: StatefulSession,
  fn: () => Promise<T>,
  isCall = true,
  isWrite = false,
  afterAdmitted?: () => void | Promise<void>
): Promise<T> {
  session.inFlight += 1;
  if (isCall) session.inFlightCalls += 1;
  if (isWrite) session.inFlightWrites = (session.inFlightWrites ?? 0) + 1;
  try {
    if (afterAdmitted) await afterAdmitted();
    return await fn();
  } finally {
    session.lastActivityMs = Date.now();
    session.inFlight -= 1;
    if (isCall) session.inFlightCalls -= 1;
    if (isWrite) {
      session.inFlightWrites = Math.max(0, (session.inFlightWrites ?? 1) - 1);
      if (session.inFlightWrites === 0) {
        session.writeTracker?.clearRollbackAbort();
        if (session.resumeAfterWrites) {
          session.resumeAfterWrites = false;
          session.closing = false;
        }
      }
    }
  }
}

/**
 * v3.10.0-rc.65 (round-3 audit) — wrap the stateful fresh-initialize body with the
 * `pendingInits` reservation so the decrement runs in a `finally` on EVERY exit path,
 * including a throw from `buildMcpServer` or the `NodeStreamableHTTPServerTransport`
 * constructor. Pre-rc.65 the `pendingInits += 1` and both constructors sat OUTSIDE the
 * try/finally, so a constructor throw skipped the decrement → the counter leaked
 * permanently, lowering the effective `maxSessions` cap by one each time until every
 * `initialize` returned 503 even with zero live sessions (the documented "always returns
 * to 0 after init" invariant was violated). Exported so the balance is unit-testable
 * with an injected throwing `fn` (NEGATIVE control).
 */
export async function runWithPendingInit<T>(registry: SessionRegistry, fn: () => Promise<T>): Promise<T> {
  if (!registry.tryReserveInit()) throw new SessionRegistryClosingError();
  try {
    return await fn();
  } finally {
    registry.releaseInit();
  }
}

/**
 * v3.7.12 M4 — parse the `maxFileBytes` ServeOptions field WITHOUT calling
 * back into `prepareServerDeps` (we only need the parsed number, not the
 * full vault). Returns `undefined` for unset / malformed / non-positive
 * input so the caller falls back to `DEFAULT_MAX_FILE_BYTES`.
 *
 * @internal — exported only for tests.
 */
export function parseMaxFileBytes(raw: string | undefined): number | undefined {
  if (raw === undefined) return undefined;
  const n = Number(raw);
  if (!Number.isFinite(n) || n <= 0 || Math.floor(n) !== n) return undefined;
  return n;
}

/**
 * Derive an honest HTTP JSON wire-byte budget from the decoded vault-file cap.
 *
 * JSON can encode one decoded control byte as the six-byte `\u00xx` form, so
 * the request budget reserves six wire bytes per admitted UTF-8 content byte,
 * plus 64 KiB for the surrounding JSON-RPC/MCP envelope. A 4 MiB floor retains
 * ordinary small-request compatibility. The result may not exceed the explicit
 * 64 MiB operational ceiling because this transport buffers bytes, decoded
 * text, and the parsed object at the same time; configurations that cannot keep
 * the worst-case one-file request inside that ceiling fail at startup instead
 * of silently advertising an unusable `maxFileBytes` value.
 *
 * @param maxFileBytes - CLI spelling of the decoded per-file byte cap.
 * @returns The admitted HTTP JSON wire-byte budget.
 * @throws {RangeError} If a valid file cap cannot fit under the operational ceiling.
 * @example
 * ```ts
 * deriveHttpBodyCap("5242880"); // worst-case-safe budget for a 5 MiB file
 * ```
 * @internal
 */
export function deriveHttpBodyCap(maxFileBytes: string | undefined): number {
  const vaultMaxBytes = parseMaxFileBytes(maxFileBytes) ?? DEFAULT_MAX_FILE_BYTES;
  const maxRepresentableFileBytes = Math.floor(
    (MAX_HTTP_JSON_BODY_BYTES - HTTP_JSON_ENVELOPE_HEADROOM_BYTES) / HTTP_JSON_ESCAPE_EXPANSION
  );
  if (vaultMaxBytes > maxRepresentableFileBytes) {
    throw new RangeError(
      `HTTP maxFileBytes=${vaultMaxBytes} cannot fit its worst-case JSON encoding under the ${MAX_HTTP_JSON_BODY_BYTES}-byte request ceiling`
    );
  }
  const escapedFileAndEnvelope = vaultMaxBytes * HTTP_JSON_ESCAPE_EXPANSION + HTTP_JSON_ENVELOPE_HEADROOM_BYTES;
  return Math.max(MIN_HTTP_JSON_BODY_BYTES, escapedFileAndEnvelope);
}

async function waitForBoundedSettlement(task: Promise<void>, timeoutMs: number): Promise<boolean> {
  if (timeoutMs <= 0) return false;
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      task.then(() => true),
      new Promise<boolean>((resolve) => {
        timer = setTimeout(() => resolve(false), timeoutMs);
      })
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

/**
 * Lifecycle owner for SDK v2's long-lived modern HTTP handler and the
 * claim-less stateless legacy requests that share its process dependencies.
 *
 * The official handler creates one registered server per modern request, but
 * the handler itself owns shared event routing and every still-open modern
 * exchange. The same lifecycle owns one aggregate tracker for default-mode
 * legacy stateless writes. Shutdown therefore closes admission synchronously,
 * gives already-admitted exchanges one bounded grace, settles write integrity,
 * and bounds SDK close before the outer HTTP shutdown closes shared deps.
 */
interface ModernHttpLifecycle {
  /** Whether a new `/mcp` request may enter protocol routing. */
  readonly accepting: boolean;
  /** Serve one already-classified modern request through the Node adapter. */
  serve(req: IncomingMessage, res: ServerResponse, body: unknown): Promise<void>;
  /** Serve one claim-less stateless legacy request under the shared write owner. */
  serveLegacyStateless(req: IncomingMessage, res: ServerResponse, body: unknown): Promise<void>;
  /** Close admission, drain boundedly, then close the official handler. */
  close(): Promise<void>;
}

function createModernHttpLifecycle(
  deps: ServerDeps,
  opts: HttpServeOptions,
  drainMs: number,
  closeMs: number,
  writeTracker: WriteRequestTracker,
  afterRequestAdmitted?: () => void | Promise<void>,
  injectedHandlerClose?: () => Promise<void>
): ModernHttpLifecycle {
  const report = (prefix: string, error: Error): void => {
    process.stderr.write(`enquire http: ${prefix} — ${error.message}\n`);
  };
  // Modern and default legacy HTTP are per request, not per session, so one
  // handler-owned tracker aggregates persistent mutations across every fresh
  // server instance. SDK close aborts transports but does not drain tool
  // callbacks; this owner keeps shared deps alive for finish-only writes and
  // explicitly rolls back cancellation-safe batches. Stateful legacy sessions
  // retain their stronger independent per-session trackers below.
  const handler: McpHttpHandler = createMcpHandler(() => buildMcpServer(deps, opts, writeTracker), {
    legacy: "reject",
    onerror: (error) => report("modern handler error", error)
  });
  const nodeHandler = toNodeHandler(handler, {
    onerror: (error) => report("modern Node adapter error", error)
  });
  let accepting = true;
  let inFlight = 0;
  let closePromise: Promise<void> | undefined;

  const serveOwned = async (
    res: ServerResponse,
    dispatch: () => Promise<void>,
    runAdmissionHook: boolean
  ): Promise<void> => {
    // This check + increment are synchronous, so shutdown can never miss a
    // request that passed admission but has not yet entered its SDK adapter.
    if (!accepting) {
      res.setHeader("Retry-After", "1");
      sendJsonRpcError(res, 503, -32000, "Server is shutting down");
      return;
    }
    inFlight += 1;
    try {
      if (runAdmissionHook && afterRequestAdmitted) await afterRequestAdmitted();
      await dispatch();
    } finally {
      inFlight -= 1;
    }
  };

  return {
    get accepting(): boolean {
      return accepting;
    },
    async serve(req, res, body): Promise<void> {
      await serveOwned(res, () => nodeHandler(req, res, body), true);
    },
    async serveLegacyStateless(req, res, body): Promise<void> {
      await serveOwned(res, () => handleStatelessRequest(req, res, deps, opts, body, writeTracker), false);
    },
    close(): Promise<void> {
      if (closePromise) return closePromise;
      accepting = false;
      writeTracker.closeAdmission("Modern HTTP shutdown closed persistent-write admission");
      const deadline = Date.now() + Math.max(0, drainMs);
      closePromise = (async () => {
        while (inFlight > 0 && Date.now() < deadline) {
          await new Promise<void>((resolve) => setTimeout(resolve, 10));
        }
        await writeTracker.abortRollbackSafe("Modern HTTP shutdown exceeded the request-drain deadline");
        await writeTracker.waitForAll();
        const closeTask = Promise.resolve()
          .then(() => (injectedHandlerClose ? injectedHandlerClose() : handler.close()))
          .catch((error) => {
            report("modern handler close failed", error instanceof Error ? error : new Error(String(error)));
          });
        if (!(await waitForBoundedSettlement(closeTask, closeMs)) && closeMs > 0) {
          process.stderr.write(`enquire http: modern handler close exceeded ${closeMs}ms; forcing TCP teardown\n`);
        }
      })();
      return closePromise;
    }
  };
}

/**
 * Build the request handler over already-prepared shared dependencies.
 *
 * @param deps - Shared vault, index, watcher, and feedback dependencies.
 * @param value - HTTP transport configuration; runtime-validated before dependency use.
 * @param out - Optional lifecycle out-parameter used by {@link startHttpServer}.
 * @param internals - Test-only body, lifecycle timing, and hook overrides.
 * @returns An async Node HTTP request handler.
 * @throws {TypeError} When HTTP transport configuration is invalid.
 * @throws {RangeError} When `maxFileBytes` cannot fit the bounded HTTP representation.
 */
export function createHttpHandler(
  deps: ServerDeps,
  value: HttpServeOptions,
  out?: { registry: SessionRegistry | null; modern?: ModernHttpLifecycle },
  internals: HttpTransportInternals = {}
): (req: IncomingMessage, res: ServerResponse) => Promise<void> {
  const opts = normalizeHttpServeOptions(value);
  const mcpPath = opts.mcpPath ?? "/mcp";
  const healthPath = opts.healthPath ?? "/health";
  const corsOrigins = opts.corsOrigins ?? [];
  const limiter = new RateLimiter(opts.rateLimitPerMinute ?? 120);
  // One worst-case-safe production cap is derived during fail-fast option
  // admission and repeated here only to retain the local numeric value. Tests
  // may replace it with a small positive limit; no CLI/config surface can raise
  // the fixed operational ceiling.
  const productionMaxBodyBytes = deriveHttpBodyCap(opts.maxFileBytes);
  const maxBodyBytes = internals.maxBodyBytes ?? productionMaxBodyBytes;
  if (!Number.isSafeInteger(maxBodyBytes) || maxBodyBytes < 1 || maxBodyBytes > MAX_HTTP_JSON_BODY_BYTES) {
    throw new TypeError(`HTTP JSON body cap must be a safe integer in [1, ${MAX_HTTP_JSON_BODY_BYTES}]`);
  }

  // v2.14.0 stateful-mode state.
  const stateful = opts.stateful === true;
  const idleTimeoutMs = opts.sessionIdleTimeoutMs ?? 30 * 60 * 1000; // 30 min default
  const maxSessions = opts.maxSessions ?? 100;
  const deleteDrainMs = Math.max(0, internals.deleteDrainMs ?? DELETE_DRAIN_MS);
  const registry = stateful ? createSessionRegistry(idleTimeoutMs) : null;
  const sharedWriteTracker = internals.modernWriteTracker ?? new WriteRequestTracker();
  const modern = createModernHttpLifecycle(
    deps,
    opts,
    Math.max(0, internals.modernDrainMs ?? MODERN_DRAIN_MS),
    Math.max(0, internals.modernCloseMs ?? MODERN_CLOSE_MS),
    sharedWriteTracker,
    internals.afterModernRequestAdmitted,
    internals.modernHandlerClose
  );
  if (out) {
    out.registry = registry;
    out.modern = modern;
  }

  return async (req, res) => {
    try {
      // v3.12.0-rc.28 — MCP Streamable HTTP requires a present invalid
      // Origin to receive 403. This is request admission, not ordinary CORS
      // decoration: reject before OPTIONS, health, auth, rate, body parsing,
      // session allocation, or MCP dispatch so DNS rebinding cannot reach a
      // side effect and a rejected request consumes no application budget.
      if (!isRequestOriginAllowed(req.headers.origin, corsOrigins)) {
        sendJsonRpcError(res, 403, -32000, "Forbidden: Origin is not allowed");
        return;
      }
      applyCors(req, res, corsOrigins);

      // OPTIONS preflight short-circuit.
      if (req.method === "OPTIONS") {
        res.statusCode = 204;
        res.end();
        return;
      }

      const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);

      // Health probe — unauthenticated, no rate-limit. Useful for
      // Tailscale/Cloudflare healthchecks. Returns just `ok` so it
      // doesn't leak version info to unauth callers.
      if (url.pathname === healthPath && req.method === "GET") {
        res.statusCode = 200;
        res.setHeader("Content-Type", "text/plain");
        res.end("ok");
        return;
      }

      if (url.pathname !== mcpPath) {
        res.statusCode = 404;
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "not found", path: url.pathname }));
        return;
      }

      // Auth: bearer token required for /mcp.
      const authHeader = req.headers.authorization;
      const tokenKey = verifyBearer(typeof authHeader === "string" ? authHeader : undefined, opts.bearerToken);
      if (tokenKey === null) {
        res.statusCode = 401;
        res.setHeader("WWW-Authenticate", 'Bearer realm="enquire-mcp"');
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "unauthorized" }));
        return;
      }

      // Rate-limit per token.
      if (!limiter.consume(tokenKey)) {
        res.statusCode = 429;
        res.setHeader("Retry-After", "60");
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "rate limit exceeded" }));
        return;
      }

      // `shutdownHttpServer` closes this gate before draining either protocol
      // era. Origin/auth/rate admission above remains observable and no new
      // body, server instance, or legacy session is allocated afterwards.
      if (!modern.accepting) {
        res.setHeader("Retry-After", "1");
        sendJsonRpcError(res, 503, -32000, "Server is shutting down");
        return;
      }

      // Match SDK v2's HTTP entry ordering: invalid media type wins before
      // body parsing and before era classification. Otherwise malformed bytes
      // under text/plain could become a 400 parse error, while a claim-less
      // JSON body could be incorrectly downgraded to the legacy leg.
      if (req.method === "POST" && !isJsonContentType(req.headers["content-type"])) {
        sendJsonRpcError(res, 415, -32000, "Unsupported Media Type: Content-Type must be application/json");
        return;
      }

      // Every POST is bounded and parsed exactly once before protocol-era
      // classification. `toWebRequest` and the selected SDK handler receive
      // this parsed value, so neither re-reads the consumed Node stream.
      let body: unknown;
      if (req.method === "POST") {
        try {
          body = await readJsonBody(req, maxBodyBytes);
        } catch (err) {
          if (err instanceof BodyTooLargeError) {
            sendJsonRpcError(res, 413, -32000, "Request body too large");
          } else {
            sendJsonRpcError(res, 400, -32700, "Parse error");
          }
          return;
        }

        // Empty bodies have no modern envelope claim and remain legacy. Every
        // non-empty JSON body goes through the SDK's own classifier. Crucially,
        // false includes malformed/unsupported modern claims, so those stay on
        // the strict modern error ladder rather than downgrading to legacy.
        if (body !== undefined) {
          const probe = await toWebRequest(req, body);
          if (!(await isLegacyRequest(probe, body))) {
            await modern.serve(req, res, body);
            return;
          }
        }
      }

      // Stateless mode (default) — POST only; fresh server+transport
      // per request. Same path as v2.6.0.
      if (!stateful || !registry) {
        if (req.method !== "POST") {
          sendJsonRpcError(res, 405, -32000, `Method ${req.method} not allowed for ${mcpPath}`);
          return;
        }
        if (body === undefined) {
          sendJsonRpcError(res, 400, -32700, "Parse error: the request body is empty");
          return;
        }
        await modern.serveLegacyStateless(req, res, body);
        return;
      }

      // ─── v2.14.0 stateful mode ─────────────────────────────────────────
      // Lazy idle-sweep on every request. Bounded work — at most O(|sessions|)
      // and cheap (Date compare per entry).
      registry.sweepIdle();

      const sessionIdHeader = req.headers["mcp-session-id"];
      const sessionId = typeof sessionIdHeader === "string" ? sessionIdHeader : undefined;

      // DELETE /mcp — explicit session termination. SDK's transport
      // handles the protocol-level details; we just route it.
      if (req.method === "DELETE") {
        if (!sessionId) {
          sendJsonRpcError(res, 400, -32000, "DELETE requires Mcp-Session-Id header");
          return;
        }
        const session = registry.sessions.get(sessionId);
        if (!session) {
          // Idempotent only once the session is genuinely absent.
          res.statusCode = 204;
          res.end();
          return;
        }
        if (session.closing) {
          // Another DELETE owns this lifecycle transition. A false 204 here
          // would be unsafe: the owner may retain the session with 409 after
          // cancelling a batch write. Tell the caller to retry instead.
          res.setHeader("Retry-After", "1");
          sendJsonRpcError(res, 409, -32001, "Session termination is already in progress; retry DELETE");
          return;
        }
        // Mark closing but retain the entry while draining. Concurrent GET/POST
        // sees `closing` and rejects; a concurrent DELETE sees the explicit
        // retryable state above. Removing the entry here would make that second
        // DELETE return a false idempotent 204 if this request later retained
        // the session after rollback.
        session.closing = true;
        const afterDeleteMarkedClosing = internals.afterDeleteMarkedClosing;
        if (afterDeleteMarkedClosing) await afterDeleteMarkedClosing(sessionId);
        // v3.11.6-rc.20 (external audit H-2) — DRAIN pre-existing in-flight
        // requests BEFORE routing the DELETE into the shared SDK transport.
        // Pre-rc.20 `handleRequest(DELETE)` — which tears the transport down at
        // the protocol level — ran FIRST, aborting the response channel of an
        // ALREADY-running tool call on the same session: a read got an empty
        // HTTP 200, and (worse) a multi-file write was interrupted mid-execution,
        // leaving a PARTIAL mutation (measured ~321/1500 files) with no response
        // boundary the client could reconcile. Marking `closing` + removing from
        // the map already blocks NEW calls from joining; now we wait for the
        // EXISTING ones to finish — delivering their complete responses and
        // completing their mutations — before terminating. The DELETE's own
        // refcount is not yet incremented here, so `inFlightCalls` reflects ONLY
        // the pre-existing POST tool calls / initialize. The ordinary wait is
        // bounded (`DELETE_DRAIN_MS`) so a stuck read cannot pin the McpServer
        // forever. Persistent writes have a stronger tail below: rollback-safe
        // batches are cancelled + restored, finish-only effects complete, and
        // DELETE retains the session with retryable 409 instead of cutting the
        // transport or losing the original tool response.
        //
        // v3.11.6-rc.21 (rc.20 re-sweep F1) — drain `inFlightCalls`, NOT `inFlight`.
        // `inFlight` also counts the long-lived GET SSE stream, which
        // `handleRequest` keeps pending for the whole stream lifetime and which
        // this very DELETE is meant to terminate — so draining `inFlight` (rc.20)
        // spun the full 5s on every clean DELETE with an open notification
        // stream. Draining `inFlightCalls` lets the DELETE close the SSE
        // immediately while still waiting for a genuine in-flight tool call.
        const drainDeadline = Date.now() + deleteDrainMs;
        while (session.inFlightCalls > 0 && Date.now() < drainDeadline) {
          await new Promise<void>((resolve) => setTimeout(resolve, 10));
        }
        if (session.inFlightCalls > 0 && (session.inFlightWrites ?? 0) > 0 && session.writeTracker) {
          // The normal drain expired while a persistent mutation was still
          // active. Abort only the batch operations that promise rollback;
          // atomic/single-effect writes are allowed to finish. In either case
          // KEEP the transport alive and return retryable 409 so the original
          // tool response can be delivered. A later DELETE can terminate the
          // now-drained session without ambiguity.
          const cancellation = await session.writeTracker.abortRollbackSafe();
          if (registry.acceptingInits && registry.sessions.get(sessionId) === session) {
            // Keep GET/POST/other DELETE requests out until the original write
            // response drains. `runWithRefcount` then clears the cancellation
            // admission latch and re-opens this exact session.
            session.resumeAfterWrites = true;
            if ((session.inFlightWrites ?? 0) === 0) {
              session.resumeAfterWrites = false;
              session.writeTracker.clearRollbackAbort();
              session.closing = false;
            }
            res.setHeader("Retry-After", "1");
            const message =
              cancellation.finishOnly > 0
                ? "Session busy: a persistent write is finishing; retry DELETE"
                : cancellation.aborted > 0
                  ? "Session busy: a batch write was cancelled and rolled back; retry DELETE"
                  : "Session busy: a persistent write response is still draining; retry DELETE";
            sendJsonRpcError(res, 409, -32001, message);
            return;
          }
          session.closing = true;
          await session.writeTracker.waitForAll();
          await session.transport.close().catch(() => {});
          await session.server.close().catch(() => {});
          sendJsonRpcError(res, 503, -32000, "Server is shutting down");
          return;
        }
        registry.sessions.delete(sessionId);
        try {
          // The DELETE itself is a lifecycle op, not a drainable call.
          await runWithRefcount(
            session,
            () => session.transport.handleRequest(req, res),
            false,
            false,
            internals.afterStatefulRequestAdmitted
          );
        } catch {
          /* shutdown errors don't matter — we're killing the session anyway */
        }
        await session.transport.close().catch(() => {});
        await session.server.close().catch(() => {});
        return;
      }

      // GET /mcp — long-lived SSE stream for server-initiated
      // notifications. The transport handles the SSE framing; we just
      // route the request to the right session.
      if (req.method === "GET") {
        if (!sessionId) {
          sendJsonRpcError(res, 400, -32000, "GET requires Mcp-Session-Id header (initialize first)");
          return;
        }
        const session = registry.sessions.get(sessionId);
        // v3.8.7 P2-10 — also reject `closing` sessions. A closing entry
        // has been removed from `sessions` so this branch is normally
        // unreachable, but the explicit check documents intent + keeps
        // us safe if someone later changes when `closing` is set.
        if (!session || session.closing) {
          sendJsonRpcError(res, 404, -32000, `Unknown session ${sessionId}`);
          return;
        }
        try {
          // v3.11.6-rc.21 (rc.20 re-sweep F1) — the SSE stream is `isCall: false`:
          // `handleRequest` stays pending for the whole stream lifetime, so it
          // must NOT be part of the DELETE/closeAll drain (which it would pin
          // forever). It still bumps `inFlight` so idle-sweep treats the session
          // as active; teardown TERMINATES this stream rather than waiting on it.
          await runWithRefcount(
            session,
            () => session.transport.handleRequest(req, res),
            false,
            false,
            internals.afterStatefulRequestAdmitted
          );
        } catch (err) {
          process.stderr.write(`enquire http: SSE error — ${err instanceof Error ? err.message : String(err)}\n`);
        }
        return;
      }

      if (req.method !== "POST") {
        sendJsonRpcError(res, 405, -32000, `Method ${req.method} not allowed for ${mcpPath}`);
        return;
      }

      // Legacy POST /mcp — either an existing session (Mcp-Session-Id
      // header) or a new initialize. The shared pre-router above already read
      // and classified this body once; only claim-less traffic reaches here.

      if (sessionId) {
        // Existing session — route to its transport.
        if (body === undefined) {
          sendJsonRpcError(res, 400, -32700, "Parse error: the request body is empty");
          return;
        }
        const session = registry.sessions.get(sessionId);
        // v3.8.7 P2-10 — same `closing` defense as the GET branch. A
        // session marked `closing` is mid-shutdown and not safe to use.
        if (!session || session.closing) {
          sendJsonRpcError(res, 404, -32000, `Unknown session ${sessionId} (it may have expired)`);
          return;
        }
        try {
          await runWithRefcount(
            session,
            () => session.transport.handleRequest(req, res, body),
            true,
            isPersistentWriteRequest(body),
            internals.afterStatefulRequestAdmitted
          );
        } catch (err) {
          process.stderr.write(
            `enquire http: stateful transport error — ${err instanceof Error ? err.message : String(err)}\n`
          );
          if (!res.headersSent) {
            sendJsonRpcError(res, 500, -32603, "Internal server error");
          }
        }
        return;
      }

      // No session id — must be a fresh `initialize`. Cap before allocating.
      // v3.8.7 P2-10 — include `pendingInits` so concurrent inits that
      // have passed this check but not yet inserted into `sessions`
      // count toward the cap. Without this, the check is a TOCTOU race
      // (N concurrent inits all see `size() < maxSessions` and overshoot).
      if (!registry.acceptingInits) {
        res.statusCode = 503;
        res.setHeader("Retry-After", "60");
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "server is shutting down" }));
        return;
      }
      if (registry.size() + registry.pendingInits >= maxSessions) {
        res.statusCode = 503;
        res.setHeader("Retry-After", "60");
        res.setHeader("Content-Type", "application/json");
        res.end(
          JSON.stringify({
            error: "max sessions reached",
            current: registry.size(),
            max: maxSessions
          })
        );
        return;
      }

      // v3.7.13 H2 — verify the body is an `initialize` JSON-RPC request
      // BEFORE we allocate a server + transport. Pre-3.7.13, any POST
      // without `Mcp-Session-Id` allocated both, then handed the body to
      // the SDK; if the body wasn't `initialize`, the SDK would either
      // reject internally or surface a protocol error — but in some
      // failure modes `onsessioninitialized` never fires and cleanup
      // never runs, leaking the McpServer + transport pair. Bearer-token
      // DoS: not anonymous, but easy for any client with a valid token
      // to fire create-and-abandon traffic until `maxSessions` blocks
      // further work. This pre-validation short-circuits the leak by
      // rejecting non-initialize POSTs at the JSON-RPC level before any
      // allocation.
      if (!isInitializeRequest(body)) {
        sendJsonRpcError(
          res,
          400,
          -32600,
          "First POST without Mcp-Session-Id header must be a JSON-RPC `initialize` request"
        );
        return;
      }

      // v3.8.7 P2-10 + v3.10.0-rc.65 — reserve the slot synchronously and run the WHOLE
      // build+connect+initialize under `runWithPendingInit`, so the reservation is released on
      // EVERY exit path — including a throw from `buildMcpServer` or the
      // `NodeStreamableHTTPServerTransport` constructor (pre-rc.65 those ran BEFORE the try/finally,
      // so a constructor throw leaked `pendingInits` permanently → eventual 503). Between the
      // reservation and the `onsessioninitialized` callback the cap-check above can see it via
      // `pendingInits` and reject concurrent inits that would overshoot the cap.
      try {
        await runWithPendingInit(registry, async () => {
          // The session object is constructed up-front so `onsessioninitialized` can insert it
          // atomically and the refcount wrapper can use it during the initialize POST itself.
          // Declared `let` + undefined so the catch can clean up PARTIAL state if a constructor
          // throws (rc.65 — the constructors are now inside the try, not before it).
          let server: ReturnType<typeof buildMcpServer> | undefined;
          let session: StatefulSession | undefined;
          let transport: InstanceType<typeof NodeStreamableHTTPServerTransport> | undefined;
          try {
            const writeTracker = new WriteRequestTracker();
            server = buildMcpServer(deps, opts, writeTracker);
            session = {
              server,
              // Filled in below once `transport` is constructed.
              transport: null as unknown as InstanceType<typeof NodeStreamableHTTPServerTransport>,
              lastActivityMs: Date.now(),
              inFlight: 0,
              inFlightCalls: 0,
              inFlightWrites: 0,
              writeTracker,
              resumeAfterWrites: false,
              closing: false
            };
            const sess = session; // captured (definitely-assigned) for the SDK callbacks
            transport = new NodeStreamableHTTPServerTransport({
              sessionIdGenerator: () => randomBytes(16).toString("hex"),
              onsessioninitialized: (sid: string) => {
                // The SDK guarantees this fires before initialize's response
                // ships, so the entry exists when subsequent requests arrive.
                // v3.11.7-rc.1 (A11) — shutdown may have closed the init
                // gate while this reserved body was building/connecting.
                // Refuse late publication; the post-handle cleanup below
                // closes the untracked server+transport pair.
                registry.registerSession(sid, sess);
              }
            });
            session.transport = transport;
            const tr = transport; // captured (definitely-assigned) for the onclose closure
            // Wire up cleanup on transport close (e.g. client disconnect mid-stream).
            tr.onclose = () => {
              const sid = tr.sessionId;
              if (sid) {
                const tracked = registry.sessions.get(sid);
                // v3.8.7 P2-10 — only mark + delete if WE inserted this entry.
                // (Defensive — onclose can fire after closeAll already removed it.)
                if (tracked) {
                  tracked.closing = true;
                  registry.sessions.delete(sid);
                }
              }
            };
            await server.connect(tr);
            await runWithRefcount(
              session,
              () => tr.handleRequest(req, res, body),
              true,
              false,
              internals.afterStatefulRequestAdmitted
            );
            if (session.closing) {
              await tr.close().catch(() => {});
              await server.close().catch(() => {});
            }
          } catch (err) {
            process.stderr.write(
              `enquire http: stateful initialize error — ${err instanceof Error ? err.message : String(err)}\n`
            );
            // Best-effort: free whatever we allocated (each guarded — a constructor may have
            // thrown before the later ones ran). If the session was already registered, mark it
            // closing + drop from map so concurrent requests don't grab a half-dead entry.
            if (session) session.closing = true;
            const sid = transport?.sessionId;
            if (sid) registry.sessions.delete(sid);
            if (transport) void transport.close().catch(() => {});
            if (server) void server.close().catch(() => {});
            if (!res.headersSent) {
              sendJsonRpcError(res, 500, -32603, "Internal server error");
            }
          }
        });
      } catch (err) {
        // The pre-check and reservation are intentionally both present:
        // closeAll can close the gate between them only at an await boundary,
        // and tryReserveInit is the atomic authority. Surface that race as a
        // retryable shutdown response, not an internal 500.
        if (err instanceof SessionRegistryClosingError) {
          res.statusCode = 503;
          res.setHeader("Retry-After", "60");
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: "server is shutting down" }));
          return;
        }
        throw err;
      }
    } catch (err) {
      // Final safety net — if anything in the outer block throws (URL
      // parse, header read), don't leave the connection hung.
      process.stderr.write(
        `enquire http: handler error — ${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`
      );
      if (!res.headersSent) {
        sendJsonRpcError(res, 500, -32603, "Internal server error");
      }
    }
  };
}

/**
 * Stateless POST handler — extracted from createHttpHandler so the
 * stateful path can keep using fresh server+transport per non-session
 * request when we want to (we don't currently). Identical to the
 * v2.6.0 default flow.
 */
async function handleStatelessRequest(
  req: IncomingMessage,
  res: ServerResponse,
  deps: ServerDeps,
  opts: HttpServeOptions,
  body: unknown,
  writeTracker: WriteRequestTracker
): Promise<void> {
  const server = buildMcpServer(deps, opts, writeTracker);
  const transport = new NodeStreamableHTTPServerTransport({ sessionIdGenerator: undefined });
  // v3.9.0-rc.16 — register cleanup BEFORE connect + make it idempotent +
  // error-safe, for parity with the stateful path's close discipline (P2-10).
  // Pre-rc.16 the `res.on("close")` registration sat AFTER `server.connect()`,
  // so a connect failure threw straight to the catch and the freshly-built
  // server + transport leaked (cleanup was never wired). The `cleanedUp` guard
  // prevents the double-close that a `res 'close'` + catch both firing would
  // otherwise cause; the `.catch` mirrors the stateful arms (lines ~378/402).
  let cleanedUp = false;
  const cleanup = () => {
    if (cleanedUp) return;
    cleanedUp = true;
    void transport.close().catch(() => {});
    void server.close().catch(() => {});
  };
  res.on("close", cleanup);
  try {
    await server.connect(transport);
    await transport.handleRequest(req, res, body);
  } catch (err) {
    process.stderr.write(`enquire http: transport error — ${err instanceof Error ? err.message : String(err)}\n`);
    if (!res.headersSent) {
      sendJsonRpcError(res, 500, -32603, "Internal server error");
    }
    // Belt-and-suspenders: if the response stream never emits 'close' (e.g.
    // connect threw before the socket was wired), free the handles now.
    cleanup();
  }
}

/**
 * Generate a fresh 32-byte base64url bearer token. Used by the
 * `enquire-mcp gen-token` subcommand.
 */
export function generateBearerToken(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * v3.8.7 P2-11 — track the SessionRegistry + ServerDeps associated with
 * each `http.Server` we hand back from `startHttpServer`. WeakMap keys
 * means we don't pin the server in memory after it's gone.
 *
 * Used by `shutdownHttpServer(server)` so callers (tests + the
 * SIGINT/SIGTERM handlers below) can drain in-flight sessions + close
 * underlying SQLite/watcher resources without threading the dep handles
 * back through their own code.
 */
interface HttpServerExtras {
  /** Stateful-mode registry; null in stateless mode. */
  registry: SessionRegistry | null;
  /** SDK v2 modern per-request handler and its bounded shutdown owner. */
  modern: ModernHttpLifecycle;
  /** Server deps so shutdownHttpServer can close watcher/fts/embed-db cleanly. */
  deps: ServerDeps;
  /** False until listen succeeds; failed startup must not publish cache bytes. */
  flushVaultCache: boolean;
  /** Retry state for the exact protocol owner published by this generation. */
  modernClosed: boolean;
  /** Retry state for the exact legacy registry published by this generation. */
  legacyClosed: boolean;
  /** Retry state for the exact listener published by this generation. */
  listenerClosed: boolean;
  /** Lazily captured dependency owner, retained until every stage succeeds. */
  cleanupOwner?: PreparedServerCleanupOwner;
  /** SIGINT/SIGTERM owner installed after listen; dropped on every shutdown. */
  onSignal?: () => void;
  /** beforeExit owner installed after listen; dropped on every shutdown. */
  onBeforeExit?: () => void;
}
const httpServerExtras = new WeakMap<HttpServer, HttpServerExtras>();
/** One teardown promise per server so concurrent programmatic callers join the
 * same protocol/write/dependency drain instead of racing it with a TCP close. */
const httpServerShutdowns = new WeakMap<HttpServer, Promise<void>>();

/**
 * v3.10.0-rc.23 — bounded grace for `server.close()`. Node's
 * `http.Server.close()` callback fires only once EVERY connection has ended, and
 * it does NOT terminate idle keep-alive sockets — so a client / reverse-proxy
 * (or a half-open socket) holding a connection open makes `close()` hang
 * indefinitely. We immediately close idle keep-alives, then force-close any
 * straggler after this grace, so shutdown can never block forever.
 *
 * This is the bound whose absence turned rc.19's signal-handler consolidation
 * into a hang: pre-rc.19 a cache-flush handler called `process.exit(0)` on its
 * own (masking the latent `close()` hang); rc.19 correctly made shutdown AWAIT
 * the full drain — but without this cap, "await the drain" became "await
 * forever" whenever a connection lingered (reproduced: a lingering socket +
 * SIGTERM hung `serve-http` indefinitely).
 */
const HTTP_CLOSE_GRACE_MS = 3000;

/**
 * Close an `http.Server` with a bounded grace (see {@link HTTP_CLOSE_GRACE_MS}).
 * Resolves as soon as `close()` completes, or after `graceMs` once stragglers
 * are force-closed — never hangs on a lingering keep-alive connection.
 *
 * @param server - Exact listener owner to close.
 * @param graceMs - Bounded wait before active stragglers are force-closed.
 * @returns A promise that resolves when Node confirms listener closure, including
 * a listener that never bound or is already stopped (`ERR_SERVER_NOT_RUNNING`).
 * @throws Any other synchronous or callback listener-close error.
 */
export function closeServerBounded(server: HttpServer, graceMs: number = HTTP_CLOSE_GRACE_MS): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const grace = setTimeout(() => {
      // Force-close active stragglers (Node ≥18.2; engines floor is ≥22.13).
      try {
        server.closeAllConnections();
      } catch {
        /* already closed / unavailable */
      }
    }, graceMs);
    if (typeof grace.unref === "function") grace.unref();
    try {
      server.close((error) => {
        clearTimeout(grace);
        // A failed `listen()` leaves the exact Server owner unbound. Node then
        // reports ERR_SERVER_NOT_RUNNING from close(), but there is no listener
        // debt to retain: treating that idempotent terminal state as a cleanup
        // failure masks the real bind error (EADDRINUSE/EACCES/EPERM) inside a
        // misleading startup AggregateError.
        if (error && (error as NodeJS.ErrnoException).code !== "ERR_SERVER_NOT_RUNNING") reject(error);
        else resolve();
      });
    } catch (error) {
      clearTimeout(grace);
      if ((error as NodeJS.ErrnoException)?.code === "ERR_SERVER_NOT_RUNNING") resolve();
      else reject(error);
      return;
    }
    // Idle keep-alive sockets won't end on their own; close them now so the
    // common case (no in-flight request) resolves immediately rather than
    // waiting out the grace.
    try {
      server.closeIdleConnections();
    } catch {
      /* best-effort */
    }
  });
}

/**
 * v3.8.7 P2-11 — graceful shutdown helper for an `http.Server` returned
 * by {@link startHttpServer}. Drains stateful sessions (if any), closes
 * the underlying TCP listener, then closes vault/fts/watcher/embed-db
 * handles owned by `prepareServerDeps`.
 *
 * Without this, callers that pass `installSignalHandlers: false` (the
 * test path, plus anyone managing the process lifecycle externally)
 * would silently leak: `httpServer.close()` alone closes only the TCP
 * accept loop, NOT the per-session McpServer + transport pairs in
 * stateful mode, and NOT the vault/fts/embed-db SQLite handles that
 * `prepareServerDeps` opens once at boot.
 *
 * Order matters:
 *   1. Drop this generation's SIGINT/SIGTERM/`beforeExit` owners so a later
 *      server in the same process cannot be terminated by this listener.
 *   2. `registry.closeAll()` — bounded ordinary request drain, followed by
 *      cancellation/rollback or completion of persistent writes, then close
 *      every transport + McpServer in stateful mode.
 *   3. `httpServer.close()` — stop accepting new connections + wait for
 *      existing ones to drain. Node's http.Server doesn't actively
 *      terminate keep-alive sockets unless we ask it to.
 *   4. Close feedback lifetime, watcher, watcherEmbedDb, vault cache, and fts5
 *      index — the same dependency order as the stdio cleanup chain.
 *
 * Idempotent: sequential and concurrent calls on the same server join the
 * same memoized teardown promise.
 */
export async function shutdownHttpServer(server: HttpServer): Promise<void> {
  const existingShutdown = httpServerShutdowns.get(server);
  if (existingShutdown) return existingShutdown;

  const shutdownTask = (async () => {
    const extras = httpServerExtras.get(server);
    if (!extras) {
      // Not from startHttpServer. Still close the TCP listener for safety.
      await closeServerBounded(server);
      return;
    }
    if (extras.onSignal) {
      process.removeListener("SIGINT", extras.onSignal);
      process.removeListener("SIGTERM", extras.onSignal);
      extras.onSignal = undefined;
    }
    if (extras.onBeforeExit) {
      process.removeListener("beforeExit", extras.onBeforeExit);
      extras.onBeforeExit = undefined;
    }
    const cleanupErrors: unknown[] = [];
    // Close both era gates synchronously, then drain independently. Legacy
    // sessions retain their stronger persistent-write tail; modern exchanges
    // receive their bounded grace before the SDK handler aborts stragglers.
    // Both protocol owners are closed before the shared deps below.
    const modernClose = extras.modernClosed
      ? Promise.resolve()
      : extras.modern.close().then(
          () => {
            extras.modernClosed = true;
          },
          (error: unknown) => {
            cleanupErrors.push(error);
          }
        );
    const legacyClose =
      extras.legacyClosed || !extras.registry
        ? Promise.resolve()
        : extras.registry.closeAll().then(
            () => {
              extras.legacyClosed = true;
            },
            (error: unknown) => {
              cleanupErrors.push(error);
            }
          );
    await Promise.all([modernClose, legacyClose]);
    if (!extras.listenerClosed) {
      try {
        await closeServerBounded(server);
        extras.listenerClosed = true;
      } catch (error) {
        cleanupErrors.push(error);
      }
    }
    // Close deps last — they own SQLite + chokidar handles that should
    // outlive in-flight requests (which we drained above). Vault doesn't
    // own a SQLite handle (no `close()` method), but it owns the
    // persistent disk cache that we should flush before exit so a
    // SIGKILL-followed-by-cold-start doesn't reread an empty vault.
    // v3.10.0-rc.44 (M6) — ORDER MATTERS, and now mirrors shutdownStdioDeps. Drain the
    // watcher FIRST, while ftsIndex + watcherEmbedDb are still OPEN: an in-flight / late
    // chokidar handler calls ftsIndex.reindexFile/dropFile + embed-db ops, and
    // watcher.close()'s flushHnswToDisk calls embedDb.computeSignature(). Pre-rc.44
    // ftsIndex.close() ran BEFORE the drain, so a handler still in flight during the
    // closeAll(5s)+closeServerBounded(3s) window threw on a closed SQLite handle and the
    // whole event (fts + embed + hnsw) was dropped. Then close the watcher's embed-db,
    // flush the vault cache, and close fts LAST.
    extras.cleanupOwner ??= createPreparedServerCleanupOwner(extras.deps, {
      flushVaultCache: extras.flushVaultCache
    });
    const dependencyFailures = await extras.cleanupOwner.cleanup();
    if (dependencyFailures.length > 0) {
      cleanupErrors.push(
        new PreparedServerCleanupError(
          `HTTP dependency shutdown was incomplete at stage(s): ${dependencyFailures
            .map(({ stage }) => stage)
            .join(", ")}`,
          dependencyFailures,
          extras.cleanupOwner
        )
      );
    }
    if (cleanupErrors.length > 0) {
      throw new AggregateError(
        cleanupErrors,
        `HTTP shutdown was incomplete; retained stage(s): ${[
          ...(extras.modernClosed ? [] : ["modern-protocol"]),
          ...(extras.legacyClosed || !extras.registry ? [] : ["legacy-protocol"]),
          ...(extras.listenerClosed ? [] : ["listener"]),
          ...extras.cleanupOwner.pendingStages
        ].join(", ")}`
      );
    }
    httpServerExtras.delete(server);
  })();
  httpServerShutdowns.set(server, shutdownTask);
  void shutdownTask.catch(() => {
    // A rejected attempt is not a terminal memoized success. Keep `extras`
    // reachable and let the next caller resume only the failed stages.
    if (httpServerShutdowns.get(server) === shutdownTask) httpServerShutdowns.delete(server);
  });
  return shutdownTask;
}

/**
 * v3.10.0-rc.19 (audit M3) — single SIGINT/SIGTERM orchestrator for the HTTP
 * transport. Returns a handler that awaits the FULL graceful teardown
 * ({@link shutdownHttpServer}: bounded ordinary stateful drain → persistent
 * write integrity tail → close the TCP listener → flush the persistent cache
 * → close fts/watcher/embed-db) and only THEN calls `exit`.
 *
 * Before rc.19, SIGINT/SIGTERM had FOUR separate listeners registered on the
 * same signal: a cache-`flush` handler, a `closeWatcher` handler, a `closeFts`
 * handler, AND the `shutdownHttpServer` handler. The flush handler called
 * `process.exit(0)` the moment its (fast) `saveDiskCache` resolved — racing
 * ahead of `shutdownHttpServer`'s up-to-5s session drain and cutting off
 * in-flight requests. The other three handlers were also pure redundancy:
 * `shutdownHttpServer` already flushes the cache and closes fts/watcher/embed-db
 * itself. Consolidating to ONE handler that awaits the whole chain removes the
 * race and the duplication.
 *
 * `exit` is injectable for tests (default `process.exit`). The returned handler
 * guards re-entry so a SIGINT-then-SIGTERM (or a double signal) can't kick off
 * two concurrent teardowns or two `exit` calls.
 */
export function makeHttpShutdownHandler(
  server: HttpServer,
  exit: (code: number) => void = (code) => process.exit(code)
): () => void {
  let running = false;
  return () => {
    if (running) return;
    running = true;
    void retryIncompleteShutdownOnce(() => shutdownHttpServer(server)).then(
      () => exit(0),
      () => {
        process.stderr.write("enquire: HTTP shutdown incomplete after bounded retry; retained cleanup debt\n");
        exit(1);
      }
    );
  };
}

/**
 * Bind and start the HTTP transport.
 *
 * @param opts - HTTP serve configuration.
 * @param internals - Test-only body and timing controls; production callers omit it.
 * @returns The underlying server for lifecycle control and inspection.
 * @throws {TypeError} When HTTP transport configuration is invalid.
 * @throws {RangeError} When `maxFileBytes` cannot fit the bounded HTTP representation.
 */
export async function startHttpServer(
  opts: HttpServeOptions,
  internals: HttpTransportInternals = {}
): Promise<HttpServer> {
  // Own every HTTP-only runtime check before opening the vault, SQLite
  // indexes, watcher, request handler, or listening socket.
  const normalizedOpts = normalizeHttpServeOptions(opts);
  const deps = await prepareServerDeps(normalizedOpts);
  // v3.8.7 P2-11 — capture the stateful registry via the out-param so
  // we can wire it into `shutdownHttpServer` via the WeakMap below.
  const handlerOut: { registry: SessionRegistry | null; modern?: ModernHttpLifecycle } = { registry: null };
  let httpServer: HttpServer | undefined;
  let startupExtras: HttpServerExtras | undefined;
  let onSignal: (() => void) | undefined;
  let onBeforeExit: (() => void) | undefined;
  let sigintInstalled = false;
  let sigtermInstalled = false;
  let beforeExitInstalled = false;
  try {
    const handler = createHttpHandler(deps, normalizedOpts, handlerOut, internals);
    const createHttpServer = internals.httpServerFactory ?? ((requestListener) => createServer(requestListener));
    httpServer = createHttpServer((req, res) => {
      void handler(req, res);
    });
    const modern = handlerOut.modern;
    if (!modern) {
      // `createHttpHandler` always publishes the lifecycle before returning.
      // Keep this fail-closed guard so a future refactor cannot start a listener
      // whose modern exchanges are absent from shutdown ownership.
      throw new Error("enquire serve-http: modern HTTP lifecycle was not initialized");
    }
    // Cache publication remains disabled until listen succeeds. A failed bind
    // owns cleanup, but must not publish a partially prepared generation.
    startupExtras = {
      registry: handlerOut.registry,
      modern,
      deps,
      flushVaultCache: false,
      modernClosed: false,
      legacyClosed: handlerOut.registry === null,
      listenerClosed: false
    };
    httpServerExtras.set(httpServer, startupExtras);
    const listener = httpServer;

    await new Promise<void>((resolve, reject) => {
      listener.once("error", reject);
      listener.listen(normalizedOpts.port, normalizedOpts.host, () => {
        listener.removeListener("error", reject);
        resolve();
      });
    });

    // Install process handlers only after a successful bind. Every
    // registration, address/banner computation, and write remains inside the
    // same post-acquire ownership boundary until the server is returned.
    if (normalizedOpts.installSignalHandlers !== false) {
      onSignal = makeHttpShutdownHandler(listener);
      process.once("SIGINT", onSignal);
      sigintInstalled = true;
      process.once("SIGTERM", onSignal);
      sigtermInstalled = true;
      let beforeExitRan = false;
      onBeforeExit = () => {
        if (beforeExitRan) return;
        beforeExitRan = true;
        void shutdownHttpServer(listener).catch(() => {
          process.stderr.write("enquire: HTTP before-exit cleanup incomplete; retained cleanup debt\n");
          process.exitCode = 1;
        });
      };
      process.on("beforeExit", onBeforeExit);
      beforeExitInstalled = true;
      startupExtras.onSignal = onSignal;
      startupExtras.onBeforeExit = onBeforeExit;
    }

    const addr = listener.address();
    const bound =
      addr && typeof addr === "object"
        ? `http://${addr.address === "::" ? "::" : addr.address}:${addr.port}`
        : `http://${normalizedOpts.host}:${normalizedOpts.port}`;
    const corsLabel =
      (normalizedOpts.corsOrigins?.length ?? 0) > 0 ? `, cors=${normalizedOpts.corsOrigins?.length ?? 0}` : "";
    const rateLabel =
      (normalizedOpts.rateLimitPerMinute ?? 120) > 0
        ? `, rate-limit=${normalizedOpts.rateLimitPerMinute ?? 120}/min`
        : "";
    if (internals.beforeStartupCommit) await internals.beforeStartupCommit(listener, deps);
    process.stderr.write(
      `${formatReadyBanner(deps)} (transport=http, bound=${bound}${normalizedOpts.mcpPath ?? "/mcp"}${corsLabel}${rateLabel})\n`
    );

    // Publishing the cache and returning the listener are the startup commit.
    // Until this exact point, rollback must remain no-flush even though bind
    // has already succeeded.
    startupExtras.flushVaultCache = true;
    return listener;
  } catch (error) {
    // Remove any partially installed process owner before tearing down the
    // protocol/listener graph it could otherwise race or retain.
    if (sigintInstalled && onSignal) process.removeListener("SIGINT", onSignal);
    if (sigtermInstalled && onSignal) process.removeListener("SIGTERM", onSignal);
    if (beforeExitInstalled && onBeforeExit) process.removeListener("beforeExit", onBeforeExit);

    const cleanupErrors: unknown[] = [];
    if (httpServer && httpServerExtras.has(httpServer)) {
      try {
        // startupExtras.flushVaultCache is still false: protocol owners and
        // the listener close before shared persistence dependencies.
        await shutdownHttpServer(httpServer);
      } catch (cleanupError) {
        if (cleanupError instanceof AggregateError) cleanupErrors.push(...cleanupError.errors);
        else cleanupErrors.push(cleanupError);
      }
    } else {
      // createHttpHandler can publish a lifecycle before a later setup throw.
      // Retain the direct local owners until each close has been attempted.
      try {
        await handlerOut.modern?.close();
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
      try {
        await handlerOut.registry?.closeAll();
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
      if (httpServer) {
        try {
          await closeServerBounded(httpServer);
        } catch (cleanupError) {
          cleanupErrors.push(cleanupError);
        }
      }
      const cleanupOwner = createPreparedServerCleanupOwner(deps, { flushVaultCache: false });
      const dependencyFailures = await cleanupOwner.cleanup();
      if (dependencyFailures.length > 0) {
        cleanupErrors.push(
          new PreparedServerCleanupError(
            `HTTP startup dependency cleanup was incomplete at stage(s): ${dependencyFailures
              .map(({ stage }) => stage)
              .join(", ")}`,
            dependencyFailures,
            cleanupOwner
          )
        );
      }
    }
    if (cleanupErrors.length > 0) {
      const retainedOwnerFailure = cleanupErrors.find(
        (cleanupError): cleanupError is PreparedServerCleanupError => cleanupError instanceof PreparedServerCleanupError
      );
      if (retainedOwnerFailure) {
        throw new PreparedServerCleanupError(
          "enquire serve-http startup failed and dependency cleanup was incomplete",
          retainedOwnerFailure.failures,
          retainedOwnerFailure.cleanupOwner,
          [error, ...cleanupErrors.filter((cleanupError) => cleanupError !== retainedOwnerFailure)]
        );
      }
      throw new AggregateError(
        [error, ...cleanupErrors],
        "enquire serve-http startup failed and dependency cleanup was incomplete"
      );
    }
    throw error;
  }
}

// Re-export the rate limiter and helpers for tests.
export { RateLimiter, readJsonBody, verifyBearer };
